//! Sampled stress evaluation and stress-limited publication for level-set designs.
//!
//! This module closes a practical product gap without pretending to solve the
//! harder stress-adjoint problem: every candidate is generated by the existing
//! compliance descent, then independently re-solved on its exact final geometry
//! and admitted only when an explicit sampled plane-strain von Mises limit is
//! satisfied. The stress maximum is resolution- and sample-scoped, not a
//! continuous-domain certificate or a KKT stress-constrained optimum.

use crate::{
    Cantilever, GridSdf, GuardedSettings, OptimizeReport, OptimizeSettings,
    optimize_compliance,
};
use fs_cutfem::quad::cut_cell_rules;
use fs_cutfem::{
    BoundaryTraction, CutElasticity, CutElasticitySolution, CutFemError, CutSdf,
    CutStabilizationScaling, DesignBoxEdge, EdgeBand, MAX_PLANE_STRAIN_STIFFNESS_RATIO,
    Quadtree,
};
use fs_material::IsotropicElastic;

const MATERIAL_STRAIN_LIMIT: f64 = 1.0;
const SOLVER_TOL: f64 = 1e-12;
const SOLVER_MAX_ITERS: usize = 60_000;
const GAUSS: f64 = 0.577_350_269_189_625_8;

/// Explicit admission limit for the sampled equivalent stress.
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct SampledStressLimit {
    /// Maximum admitted sampled plane-strain von Mises stress.
    pub max_von_mises: f64,
    /// Absolute numerical allowance added to `max_von_mises`.
    pub absolute_tolerance: f64,
}

impl SampledStressLimit {
    /// Construct a finite positive limit with a finite nonnegative allowance.
    ///
    /// # Errors
    /// Refuses non-finite, non-positive limits and invalid tolerances.
    pub fn new(max_von_mises: f64, absolute_tolerance: f64) -> Result<Self, CutFemError> {
        if !(max_von_mises.is_finite() && max_von_mises > 0.0) {
            return Err(invalid("sampled stress limit must be finite and strictly positive"));
        }
        if !(absolute_tolerance.is_finite() && absolute_tolerance >= 0.0) {
            return Err(invalid("sampled stress tolerance must be finite and nonnegative"));
        }
        let admitted = max_von_mises + absolute_tolerance;
        if !admitted.is_finite() {
            return Err(invalid("sampled stress limit plus tolerance overflowed"));
        }
        Ok(Self { max_von_mises, absolute_tolerance })
    }

    #[must_use]
    pub fn admitted_max(self) -> f64 {
        self.max_von_mises + self.absolute_tolerance
    }
}

/// Independent final-state mechanics and sampled-stress evidence.
#[derive(Debug, Clone, PartialEq)]
pub struct SampledStressEvaluation {
    /// Canonical discrete external work `b^T u`.
    pub compliance: f64,
    /// Cut-quadrature material area.
    pub volume: f64,
    /// Maximum von Mises value over the declared sample set.
    pub sampled_max_von_mises: f64,
    /// Point where the deterministic traversal first attained that maximum.
    pub max_location: [f64; 2],
    /// Number of material stress probes that contributed.
    pub sample_count: usize,
    /// FNV-64 fingerprint of the exact level-set node bits.
    pub snapshot: u64,
}

/// One stress-limited candidate trajectory.
#[derive(Debug, Clone)]
pub struct StressGuardedCandidate {
    /// Zero-based deterministic candidate index.
    pub index: usize,
    /// Interface move limit used for this complete trajectory.
    pub move_cells: f64,
    /// Independent final mechanics/stress evaluation, if available.
    pub evaluation: Option<SampledStressEvaluation>,
    /// Whether final cut-quadrature area met the requested volume bound.
    pub volume_feasible: bool,
    /// Whether the deterministic sampled maximum met the stress bound.
    pub stress_feasible: bool,
    /// Whether the compliance improvement rule was met.
    pub improvement_gate: bool,
    /// Retained typed refusal when evolution or final evaluation failed.
    pub refusal: Option<String>,
}

/// Why stress-limited bounded publication stopped.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum StressGuardedStop {
    Accepted,
    NoConstraintFeasibleCandidate,
    NoImprovingCandidate,
    AllCandidatesRefused,
}

/// Bounded stress-limited publication evidence.
#[derive(Debug, Clone)]
pub struct StressGuardedReport {
    /// Independent mechanics/stress evaluation of the starting geometry.
    pub baseline: SampledStressEvaluation,
    /// Declared sampled-stress admission limit.
    pub limit: SampledStressLimit,
    /// Bounded candidate attempts in deterministic move-size order.
    pub candidates: Vec<StressGuardedCandidate>,
    /// Search termination reason.
    pub stop: StressGuardedStop,
    /// Independently evaluated published design, if accepted.
    pub accepted: Option<SampledStressEvaluation>,
    /// Evolution trajectory for the accepted geometry.
    pub trajectory: Option<OptimizeReport>,
    /// Move limit used by the accepted trajectory.
    pub accepted_move_cells: Option<f64>,
}

fn invalid(what: impl Into<String>) -> CutFemError {
    CutFemError::InvalidElasticityInput { what: what.into() }
}

fn snapshot(phi: &GridSdf) -> u64 {
    let mut hash = 0xcbf2_9ce4_8422_2325u64;
    for value in phi.nodes() {
        for byte in value.to_bits().to_le_bytes() {
            hash ^= u64::from(byte);
            hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
        }
    }
    hash
}

fn validate(
    phi: &GridSdf,
    fixture: Cantilever,
    settings: OptimizeSettings,
) -> Result<(EdgeBand, IsotropicElastic, f64, f64), CutFemError> {
    let expected = 1usize.checked_shl(settings.level)
        .ok_or_else(|| invalid("stress-evaluation grid level exceeds platform address space"))?;
    if phi.n() != expected {
        return Err(invalid(format!(
            "stress-evaluation SDF has {} cells per side but level {} requires {expected}",
            phi.n(), settings.level
        )));
    }
    if phi.nodes().iter().any(|value| !value.is_finite()) {
        return Err(invalid("stress evaluation requires finite level-set nodes"));
    }
    if !(fixture.load.is_finite() && fixture.load > 0.0) {
        return Err(invalid("stress-evaluation cantilever load must be finite and positive"));
    }
    let support = EdgeBand::new(
        DesignBoxEdge::Right,
        0.5 - fixture.band,
        0.5 + fixture.band,
    ).map_err(|error| invalid(format!("stress-evaluation load band refused: {error}")))?;
    if !(settings.youngs.is_finite() && settings.youngs > 0.0) {
        return Err(invalid("stress evaluation requires finite positive Young's modulus"));
    }
    if !(settings.poisson.is_finite() && settings.poisson > -1.0 && settings.poisson < 0.5) {
        return Err(invalid("stress evaluation requires Poisson ratio in (-1, 0.5)"));
    }
    let material = IsotropicElastic::new(settings.youngs, settings.poisson, MATERIAL_STRAIN_LIMIT)
        .map_err(|error| invalid(format!("stress-evaluation material card refused: {error}")))?;
    let (lambda, mu) = material.lame();
    let ratio = (lambda + 2.0 * mu) / mu;
    if !(lambda.is_finite() && mu.is_finite() && mu > 0.0
        && ratio.is_finite() && ratio <= MAX_PLANE_STRAIN_STIFFNESS_RATIO)
    {
        return Err(invalid(format!(
            "stress-evaluation plane-strain stiffness ratio {ratio} exceeds the admitted regime"
        )));
    }
    Ok((support, material, lambda, mu))
}

fn strain_at(
    grid: &Quadtree,
    solution: &CutElasticitySolution,
    point: [f64; 2],
) -> Option<[f64; 3]> {
    let level = grid.max_level();
    let nf = f64::from(1u32 << level);
    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let ci = ((point[0] * nf).floor().clamp(0.0, nf - 1.0)) as u32;
    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    let cj = ((point[1] * nf).floor().clamp(0.0, nf - 1.0)) as u32;
    let cell = (level, ci, cj);
    let (lo, hi) = grid.rect(cell);
    let corners = grid.corner_nodes(cell);
    let nodal = solution.nodal();
    let mut values = [[0.0; 2]; 4];
    for (index, corner) in corners.iter().enumerate() {
        values[index] = *nodal.get(corner)?;
    }
    let hx = hi[0] - lo[0];
    let hy = hi[1] - lo[1];
    let xi = ((point[0] - lo[0]) / hx).clamp(0.0, 1.0);
    let eta = ((point[1] - lo[1]) / hy).clamp(0.0, 1.0);
    let gradients = [
        [-(1.0 - eta) / hx, -(1.0 - xi) / hy],
        [(1.0 - eta) / hx, -xi / hy],
        [eta / hx, xi / hy],
        [-eta / hx, (1.0 - xi) / hy],
    ];
    let mut grad_u = [[0.0; 2]; 2];
    for a in 0..4 {
        for component in 0..2 {
            grad_u[component][0] += gradients[a][0] * values[a][component];
            grad_u[component][1] += gradients[a][1] * values[a][component];
        }
    }
    Some([
        grad_u[0][0],
        grad_u[1][1],
        f64::midpoint(grad_u[0][1], grad_u[1][0]),
    ])
}

fn von_mises_plane_strain(lambda: f64, mu: f64, strain: [f64; 3]) -> f64 {
    let sxx = (lambda + 2.0 * mu) * strain[0] + lambda * strain[1];
    let syy = lambda * strain[0] + (lambda + 2.0 * mu) * strain[1];
    let szz = lambda * (strain[0] + strain[1]);
    let sxy = 2.0 * mu * strain[2];
    fs_material::tensor::von_mises(&[sxx, syy, szz, sxy, 0.0, 0.0])
}

fn full_cell_points(lo: [f64; 2], hi: [f64; 2]) -> [[f64; 2]; 5] {
    let mid = [f64::midpoint(lo[0], hi[0]), f64::midpoint(lo[1], hi[1])];
    let half = [0.5 * (hi[0] - lo[0]), 0.5 * (hi[1] - lo[1])];
    [
        [mid[0] - GAUSS * half[0], mid[1] - GAUSS * half[1]],
        [mid[0] + GAUSS * half[0], mid[1] - GAUSS * half[1]],
        [mid[0] + GAUSS * half[0], mid[1] + GAUSS * half[1]],
        [mid[0] - GAUSS * half[0], mid[1] + GAUSS * half[1]],
        mid,
    ]
}

fn observe_stress(
    grid: &Quadtree,
    solution: &CutElasticitySolution,
    lambda: f64,
    mu: f64,
    point: [f64; 2],
    max_stress: &mut f64,
    max_location: &mut [f64; 2],
    sample_count: &mut usize,
) -> Result<(), CutFemError> {
    if let Some(strain) = strain_at(grid, solution, point) {
        let stress = von_mises_plane_strain(lambda, mu, strain);
        if !stress.is_finite() || stress < 0.0 {
            return Err(invalid("sampled plane-strain von Mises stress is invalid"));
        }
        *sample_count = sample_count.checked_add(1)
            .ok_or_else(|| invalid("sampled stress count overflowed"))?;
        if stress > *max_stress {
            *max_stress = stress;
            *max_location = point;
        }
    }
    Ok(())
}

/// Independently solve one exact geometry and evaluate deterministic sampled
/// plane-strain von Mises stress.
///
/// Fully material cells use four tensor-Gauss probes plus the center. Cut cells
/// use every retained bulk and interface quadrature point from depth-2 cut-cell
/// rules. The reported maximum is only over those samples.
///
/// # Errors
/// Refuses malformed inputs, canonical CutFEM failures, or invalid stress data.
pub fn evaluate_sampled_stress(
    phi: &GridSdf,
    fixture: Cantilever,
    settings: OptimizeSettings,
) -> Result<SampledStressEvaluation, CutFemError> {
    let (support, material, lambda, mu) = validate(phi, fixture, settings)?;
    let grid = Quadtree::uniform(settings.level);
    let clamp = |x: f64, _y: f64| x < 1e-9;
    let traction = |_: f64, _: f64| [0.0, -fixture.load];
    let solver = CutElasticity {
        grid: &grid,
        sdf: phi,
        material: &material,
        nitsche_beta: 20.0,
        ghost_gamma: 0.5,
        stabilization_scaling: CutStabilizationScaling::LongitudinalModulus,
        quad_depth: 2,
        clamp: Some(&clamp),
        boundary_traction: None,
        traction_free_interface: true,
        solver_tol: SOLVER_TOL,
        solver_max_iters: SOLVER_MAX_ITERS,
    };
    let solution = solver.solve_with_boundary_traction(
        &|_, _| [0.0, 0.0],
        &|_, _| [0.0, 0.0],
        BoundaryTraction::EdgeBand { support, value: &traction },
    )?;
    let compliance = solution.compliance();
    let volume = crate::optimize::material_volume(&grid, phi);
    if !(compliance.is_finite() && compliance >= 0.0 && volume.is_finite() && volume > 0.0) {
        return Err(invalid("stress evaluation produced invalid compliance or material area"));
    }

    let mut sampled_max = 0.0_f64;
    let mut max_location = [0.0, 0.0];
    let mut sample_count = 0usize;
    for cell in grid.leaves() {
        let (lo, hi) = grid.rect(cell);
        let enclosure = phi.enclose(lo, hi);
        if enclosure.lo() > 0.0 {
            continue;
        }
        if enclosure.hi() < 0.0 {
            for point in full_cell_points(lo, hi) {
                observe_stress(
                    &grid, &solution, lambda, mu, point,
                    &mut sampled_max, &mut max_location, &mut sample_count,
                )?;
            }
        } else {
            let rules = cut_cell_rules(phi, lo, hi, 2);
            for &(point, weight) in &rules.bulk {
                if weight > 0.0 {
                    observe_stress(
                        &grid, &solution, lambda, mu, point,
                        &mut sampled_max, &mut max_location, &mut sample_count,
                    )?;
                }
            }
            for &(point, weight, _) in &rules.iface {
                if weight > 0.0 {
                    observe_stress(
                        &grid, &solution, lambda, mu, point,
                        &mut sampled_max, &mut max_location, &mut sample_count,
                    )?;
                }
            }
        }
    }
    if sample_count == 0 {
        return Err(invalid("stress evaluation found no material stress samples"));
    }
    Ok(SampledStressEvaluation {
        compliance,
        volume,
        sampled_max_von_mises: sampled_max,
        max_location,
        sample_count,
        snapshot: snapshot(phi),
    })
}

fn validate_guarded(
    settings: OptimizeSettings,
    guarded: GuardedSettings,
    limit: SampledStressLimit,
) -> Result<(), CutFemError> {
    SampledStressLimit::new(limit.max_von_mises, limit.absolute_tolerance)?;
    if settings.iterations == 0 {
        return Err(invalid("stress-limited optimization requires at least one evolution iteration"));
    }
    if !(settings.move_cells.is_finite() && settings.move_cells > 0.0) {
        return Err(invalid("stress-limited optimization requires finite positive move_cells"));
    }
    if !(settings.volfrac.is_finite() && settings.volfrac > 0.0 && settings.volfrac <= 1.0) {
        return Err(invalid("stress-limited optimization requires volfrac in (0, 1]"));
    }
    if guarded.max_candidates == 0 || guarded.max_candidates > 64 {
        return Err(invalid("stress-limited max_candidates must lie in [1, 64]"));
    }
    if !(guarded.contraction.is_finite() && guarded.contraction > 0.0 && guarded.contraction < 1.0) {
        return Err(invalid("stress-limited contraction must lie strictly between zero and one"));
    }
    if !(guarded.volume_tolerance.is_finite() && guarded.volume_tolerance >= 0.0
        && guarded.volume_tolerance <= 1.0)
    {
        return Err(invalid("stress-limited volume_tolerance must lie in [0, 1]"));
    }
    if !(guarded.min_relative_improvement.is_finite()
        && guarded.min_relative_improvement >= 0.0
        && guarded.min_relative_improvement < 1.0)
    {
        return Err(invalid("stress-limited min_relative_improvement must lie in [0, 1)"));
    }
    Ok(())
}

/// Bounded transactional compliance search with explicit sampled-stress and
/// material-area admission on every exact returned candidate.
///
/// Candidate generation remains the compliance shape gradient. This routine is
/// therefore a stress-limited selector, not a stress-adjoint/KKT optimizer.
///
/// # Errors
/// Refuses malformed controls or a baseline mechanics/stress evaluation.
pub fn optimize_compliance_stress_guarded(
    phi: &mut GridSdf,
    fixture: Cantilever,
    settings: OptimizeSettings,
    guarded: GuardedSettings,
    limit: SampledStressLimit,
) -> Result<StressGuardedReport, CutFemError> {
    validate_guarded(settings, guarded, limit)?;
    let baseline = evaluate_sampled_stress(phi, fixture, settings)?;
    let volume_limit = settings.volfrac + guarded.volume_tolerance;
    let stress_limit = limit.admitted_max();
    let baseline_constraints = baseline.volume <= volume_limit
        && baseline.sampled_max_von_mises <= stress_limit;
    let improvement_limit = baseline.compliance * (1.0 - guarded.min_relative_improvement);
    let origin = phi.clone();
    let mut candidates = Vec::with_capacity(guarded.max_candidates);
    let mut best: Option<(GridSdf, SampledStressEvaluation, OptimizeReport, f64)> = None;
    let mut move_cells = settings.move_cells;
    let mut any_final = false;
    let mut any_constraint_feasible = false;

    for index in 0..guarded.max_candidates {
        let mut trial_settings = settings;
        trial_settings.move_cells = move_cells;
        let mut trial = origin.clone();
        match optimize_compliance(&mut trial, fixture, trial_settings) {
            Ok(trajectory) => match evaluate_sampled_stress(&trial, fixture, settings) {
                Ok(evaluation) => {
                    any_final = true;
                    let volume_feasible = evaluation.volume <= volume_limit;
                    let stress_feasible = evaluation.sampled_max_von_mises <= stress_limit;
                    let constraint_feasible = volume_feasible && stress_feasible;
                    any_constraint_feasible |= constraint_feasible;
                    let improvement_gate = !baseline_constraints
                        || evaluation.compliance <= improvement_limit;
                    if constraint_feasible && improvement_gate {
                        let replace = best.as_ref().is_none_or(|(_, current, _, _)| {
                            evaluation.compliance < current.compliance
                        });
                        if replace {
                            best = Some((trial, evaluation.clone(), trajectory.clone(), move_cells));
                        }
                    }
                    candidates.push(StressGuardedCandidate {
                        index,
                        move_cells,
                        evaluation: Some(evaluation),
                        volume_feasible,
                        stress_feasible,
                        improvement_gate,
                        refusal: None,
                    });
                }
                Err(error) => candidates.push(StressGuardedCandidate {
                    index,
                    move_cells,
                    evaluation: None,
                    volume_feasible: false,
                    stress_feasible: false,
                    improvement_gate: false,
                    refusal: Some(format!("{error:?}")),
                }),
            },
            Err(error) => candidates.push(StressGuardedCandidate {
                index,
                move_cells,
                evaluation: None,
                volume_feasible: false,
                stress_feasible: false,
                improvement_gate: false,
                refusal: Some(format!("{error:?}")),
            }),
        }
        move_cells *= guarded.contraction;
    }

    if let Some((accepted_phi, accepted, trajectory, accepted_move_cells)) = best {
        *phi = accepted_phi;
        return Ok(StressGuardedReport {
            baseline,
            limit,
            candidates,
            stop: StressGuardedStop::Accepted,
            accepted: Some(accepted),
            trajectory: Some(trajectory),
            accepted_move_cells: Some(accepted_move_cells),
        });
    }
    let stop = if !any_final {
        StressGuardedStop::AllCandidatesRefused
    } else if !any_constraint_feasible {
        StressGuardedStop::NoConstraintFeasibleCandidate
    } else {
        StressGuardedStop::NoImprovingCandidate
    };
    Ok(StressGuardedReport {
        baseline,
        limit,
        candidates,
        stop,
        accepted: None,
        trajectory: None,
        accepted_move_cells: None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn beam(level: u32) -> GridSdf {
        GridSdf::from_fn(1usize << level, &|_, y| (y - 0.5).abs() - 0.35)
    }

    fn settings(level: u32) -> OptimizeSettings {
        OptimizeSettings { level, iterations: 1, nucleation_period: 0, ..OptimizeSettings::default() }
    }

    #[test]
    fn sampled_stress_scales_linearly_with_load() {
        let phi = beam(3);
        let one = evaluate_sampled_stress(
            &phi, Cantilever { load: 1.0, band: 0.125 }, settings(3)
        ).expect("unit load");
        let two = evaluate_sampled_stress(
            &phi, Cantilever { load: 2.0, band: 0.125 }, settings(3)
        ).expect("double load");
        let stress_ratio = two.sampled_max_von_mises / one.sampled_max_von_mises;
        let compliance_ratio = two.compliance / one.compliance;
        assert!((stress_ratio - 2.0).abs() < 1e-8);
        assert!((compliance_ratio - 4.0).abs() < 1e-8);
        assert_eq!(one.sample_count, two.sample_count);
        assert_eq!(one.snapshot, two.snapshot);
    }

    #[test]
    fn impossible_stress_gate_is_transactional() {
        let mut phi = beam(3);
        let before = phi.nodes().to_vec();
        let report = optimize_compliance_stress_guarded(
            &mut phi,
            Cantilever { load: 1.0, band: 0.125 },
            OptimizeSettings {
                level: 3,
                iterations: 1,
                volfrac: 1.0,
                move_cells: 0.02,
                nucleation_period: 0,
                ..OptimizeSettings::default()
            },
            GuardedSettings {
                max_candidates: 2,
                contraction: 0.5,
                volume_tolerance: 0.0,
                min_relative_improvement: 0.0,
            },
            SampledStressLimit::new(1e-30, 0.0).unwrap(),
        ).expect("bounded refusal is data");
        assert_ne!(report.stop, StressGuardedStop::Accepted);
        assert!(report.accepted.is_none());
        assert_eq!(phi.nodes(), before);
    }
}
