//! HEX-DOMINANT MESHING via octahedral frame fields (plan §7.5, bead
//! wqd.18; [F] — behind `frontier-hexmesh`, OFF the critical path, and
//! honestly flagged as the hardest meshing deliverable in the plan).
//!
//! FRAME REPRESENTATION: the SH9 (band-4 spherical-harmonic)
//! parameterization is realized as a FIXED SPHERICAL SAMPLING of the
//! degree-4 octahedral polynomial `F_R(d) = Σ (R·axes)⁴·d` — the
//! sample vector is a LINEAR IMAGE of the SH9 coefficients, so linear
//! MBO diffusion in sample space is exactly SH9 diffusion; the exact
//! Wigner-D machinery is the named growth path (CONTRACT no-claim).
//! MBO iteration: diffuse (graph Laplacian average) → PROJECT back to
//! the octahedral variety (best rotation by deterministic seeded hill
//! climbing over quaternions). Boundary frames stay normal-aligned.
//!
//! SINGULARITIES: around every interior lattice edge, the composition
//! of nearest-octahedral matchings between the four surrounding cells
//! must be the identity; edges where it is not form the singular
//! graph. HEX EXTRACTION ships for the polycube-class geometries the
//! fallback produces (axis-aligned labeling); when the frame field is
//! not integrable the POLYCUBE FALLBACK engages with a documented
//! decision and the honest-alternatives diagnostic (IGA/CutFEM).

/// A unit quaternion rotation (w, x, y, z).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct Quat {
    /// Scalar part.
    pub w: f64,
    /// Vector part.
    pub x: f64,
    /// y.
    pub y: f64,
    /// z.
    pub z: f64,
}

impl Quat {
    /// Identity.
    #[must_use]
    pub fn identity() -> Quat {
        Quat {
            w: 1.0,
            x: 0.0,
            y: 0.0,
            z: 0.0,
        }
    }

    fn normalize(self) -> Quat {
        let n = f64::sqrt(self.w * self.w + self.x * self.x + self.y * self.y + self.z * self.z)
            .max(1e-300);
        Quat {
            w: self.w / n,
            x: self.x / n,
            y: self.y / n,
            z: self.z / n,
        }
    }

    fn mul(self, o: Quat) -> Quat {
        Quat {
            w: self.w * o.w - self.x * o.x - self.y * o.y - self.z * o.z,
            x: self.w * o.x + self.x * o.w + self.y * o.z - self.z * o.y,
            y: self.w * o.y - self.x * o.z + self.y * o.w + self.z * o.x,
            z: self.w * o.z + self.x * o.y - self.y * o.x + self.z * o.w,
        }
    }

    /// Rotate a vector.
    #[must_use]
    pub fn rotate(self, v: [f64; 3]) -> [f64; 3] {
        let q = self;
        let u = [q.x, q.y, q.z];
        let s = q.w;
        let cross = |a: [f64; 3], b: [f64; 3]| {
            [
                a[1] * b[2] - a[2] * b[1],
                a[2] * b[0] - a[0] * b[2],
                a[0] * b[1] - a[1] * b[0],
            ]
        };
        let uv = cross(u, v);
        let uuv = cross(u, uv);
        [
            v[0] + 2.0 * (s * uv[0] + uuv[0]),
            v[1] + 2.0 * (s * uv[1] + uuv[1]),
            v[2] + 2.0 * (s * uv[2] + uuv[2]),
        ]
    }
}

/// The fixed sampling directions (the 26 lattice directions,
/// normalized — a spherical design adequate for band-4 content).
fn sample_dirs() -> Vec<[f64; 3]> {
    let mut dirs = Vec::with_capacity(26);
    for z in -1i32..=1 {
        for y in -1i32..=1 {
            for x in -1i32..=1 {
                if x == 0 && y == 0 && z == 0 {
                    continue;
                }
                let v = [f64::from(x), f64::from(y), f64::from(z)];
                let n = f64::sqrt(v[0] * v[0] + v[1] * v[1] + v[2] * v[2]);
                dirs.push([v[0] / n, v[1] / n, v[2] / n]);
            }
        }
    }
    dirs
}

/// The SH9-class sample vector of the octahedral frame with rotation
/// `q`: values of `Σ_axes ⟨axis, d⟩⁴` at the fixed directions.
#[must_use]
pub fn frame_samples(q: Quat, dirs: &[[f64; 3]]) -> Vec<f64> {
    let ax = q.rotate([1.0, 0.0, 0.0]);
    let ay = q.rotate([0.0, 1.0, 0.0]);
    let az = q.rotate([0.0, 0.0, 1.0]);
    dirs.iter()
        .map(|d| {
            let dot = |a: [f64; 3]| a[0] * d[0] + a[1] * d[1] + a[2] * d[2];
            // det::powi: pinned (x²)² order in every build mode (4xnt);
            // bit-neutral here — literal-4 lowerings already squared.
            fs_math::det::powi(dot(ax), 4)
                + fs_math::det::powi(dot(ay), 4)
                + fs_math::det::powi(dot(az), 4)
        })
        .collect()
}

/// The 24 rotations of the cube group as quaternions (deterministic
/// order) — the matching set for singularity extraction.
#[must_use]
pub fn cube_group() -> Vec<Quat> {
    let mut out = Vec::with_capacity(24);
    let s2 = std::f64::consts::FRAC_1_SQRT_2;
    // Identity + face rotations (90/180/270 about x, y, z) + edge/vertex
    // rotations; generated by composing the two generators and
    // deduplicating — deterministic and exact enough at f64.
    let gx = Quat {
        w: s2,
        x: s2,
        y: 0.0,
        z: 0.0,
    };
    let gz = Quat {
        w: s2,
        x: 0.0,
        y: 0.0,
        z: s2,
    };
    let mut frontier = vec![Quat::identity()];
    let close = |a: Quat, b: Quat| -> bool {
        // q and -q are the same rotation.
        let d1 = (a.w - b.w).abs() + (a.x - b.x).abs() + (a.y - b.y).abs() + (a.z - b.z).abs();
        let d2 = (a.w + b.w).abs() + (a.x + b.x).abs() + (a.y + b.y).abs() + (a.z + b.z).abs();
        d1 < 1e-9 || d2 < 1e-9
    };
    while let Some(q) = frontier.pop() {
        if out.iter().any(|&o| close(o, q)) {
            continue;
        }
        out.push(q);
        frontier.push(q.mul(gx).normalize());
        frontier.push(q.mul(gz).normalize());
    }
    out.sort_by(|a, b| {
        b.w.abs()
            .total_cmp(&a.w.abs())
            .then(a.x.total_cmp(&b.x))
            .then(a.y.total_cmp(&b.y))
            .then(a.z.total_cmp(&b.z))
    });
    out
}

/// The frame field on a cell lattice over a box-like domain.
#[derive(Debug, Clone)]
pub struct FrameField {
    /// Lattice dims (cells).
    pub dims: [usize; 3],
    /// Per-cell frame rotations.
    pub frames: Vec<Quat>,
}

fn idx(dims: [usize; 3], i: usize, j: usize, k: usize) -> usize {
    (k * dims[1] + j) * dims[0] + i
}

/// The SH9-sample Dirichlet energy of the field (the MBO monotonicity
/// witness): Σ over 6-neighbor pairs of ‖samples(a) − samples(b)‖².
#[must_use]
pub fn dirichlet_energy(field: &FrameField) -> f64 {
    let dirs = sample_dirs();
    let [nx, ny, nz] = field.dims;
    let samples: Vec<Vec<f64>> = field
        .frames
        .iter()
        .map(|&q| frame_samples(q, &dirs))
        .collect();
    let mut acc = 0.0f64;
    for k in 0..nz {
        for j in 0..ny {
            for i in 0..nx {
                let a = idx(field.dims, i, j, k);
                let mut pair = |b: usize| {
                    acc += samples[a]
                        .iter()
                        .zip(&samples[b])
                        .map(|(x, y)| (x - y) * (x - y))
                        .sum::<f64>();
                };
                if i + 1 < nx {
                    pair(idx(field.dims, i + 1, j, k));
                }
                if j + 1 < ny {
                    pair(idx(field.dims, i, j + 1, k));
                }
                if k + 1 < nz {
                    pair(idx(field.dims, i, j, k + 1));
                }
            }
        }
    }
    acc
}

/// Project a sample vector back to the octahedral variety: the best
/// rotation by deterministic seeded search (24 cube rotations plus a
/// counter-based quaternion cloud) refined by shrinking-step hill
/// climbing. Deterministic; ties break toward the earlier candidate.
#[must_use]
pub fn project_to_frame(target: &[f64], dirs: &[[f64; 3]], seed: u64) -> Quat {
    let score = |q: Quat| -> f64 {
        let s = frame_samples(q, dirs);
        -s.iter()
            .zip(target)
            .map(|(a, b)| (a - b) * (a - b))
            .sum::<f64>()
    };
    let unit = |k: u64| -> f64 {
        let mut z = seed ^ 0x9e37_79b9_7f4a_7c15u64.wrapping_mul(k + 1);
        z = (z ^ (z >> 30)).wrapping_mul(0xbf58_476d_1ce4_e5b9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94d0_49bb_1331_11eb);
        z ^= z >> 31;
        (z >> 11) as f64 / (1u64 << 53) as f64 * 2.0 - 1.0
    };
    let mut best = Quat::identity();
    let mut best_s = score(best);
    for (c, &q) in cube_group().iter().enumerate() {
        let _ = c;
        let s = score(q);
        if s > best_s {
            best = q;
            best_s = s;
        }
    }
    for c in 0..8u64 {
        let q = Quat {
            w: unit(4 * c),
            x: unit(4 * c + 1),
            y: unit(4 * c + 2),
            z: unit(4 * c + 3),
        }
        .normalize();
        let s = score(q);
        if s > best_s {
            best = q;
            best_s = s;
        }
    }
    // Shrinking-step local refinement.
    let mut step = 0.2f64;
    for round in 0..40u64 {
        let mut improved = false;
        for axis in 0..3 {
            for sign in [-1.0f64, 1.0] {
                let mut d = [0.0f64; 3];
                d[axis] = sign * step;
                let half = f64::sqrt(d[0] * d[0] + d[1] * d[1] + d[2] * d[2]) / 2.0;
                let (sw, sv) = ((1.0 - half * half).max(0.0).sqrt(), 0.5);
                let dq = Quat {
                    w: sw,
                    x: d[0] * sv,
                    y: d[1] * sv,
                    z: d[2] * sv,
                }
                .normalize();
                let cand = best.mul(dq).normalize();
                let s = score(cand);
                if s > best_s {
                    best = cand;
                    best_s = s;
                    improved = true;
                }
            }
        }
        if !improved {
            step *= 0.5;
            if step < 1e-6 {
                break;
            }
        }
        let _ = round;
    }
    best
}

/// One MBO iteration: diffuse the SH9-class samples over the 6-neighbor
/// graph, project every interior cell back to the variety; boundary
/// cells stay pinned (normal-aligned by construction on the box
/// lattice — the identity frame IS normal-aligned to axis boundaries).
pub fn mbo_step(field: &mut FrameField, seed: u64) {
    let dirs = sample_dirs();
    let [nx, ny, nz] = field.dims;
    let samples: Vec<Vec<f64>> = field
        .frames
        .iter()
        .map(|&q| frame_samples(q, &dirs))
        .collect();
    let mut next = field.frames.clone();
    for k in 0..nz {
        for j in 0..ny {
            for i in 0..nx {
                let boundary =
                    i == 0 || j == 0 || k == 0 || i == nx - 1 || j == ny - 1 || k == nz - 1;
                if boundary {
                    continue; // pinned: normal-aligned on the box
                }
                let a = idx(field.dims, i, j, k);
                let mut avg = vec![0.0f64; dirs.len()];
                let mut count = 0.0f64;
                let mut add = |b: usize| {
                    for (av, sv) in avg.iter_mut().zip(&samples[b]) {
                        *av += sv;
                    }
                    count += 1.0;
                };
                add(idx(field.dims, i - 1, j, k));
                add(idx(field.dims, i + 1, j, k));
                add(idx(field.dims, i, j - 1, k));
                add(idx(field.dims, i, j + 1, k));
                add(idx(field.dims, i, j, k - 1));
                add(idx(field.dims, i, j, k + 1));
                for av in &mut avg {
                    *av /= count;
                }
                next[a] = project_to_frame(&avg, &dirs, seed ^ (a as u64));
            }
        }
    }
    field.frames = next;
}

/// The nearest cube-group matching from frame `a` to frame `b`.
fn matching(a: Quat, b: Quat, group: &[Quat]) -> usize {
    // Find g minimizing the sample distance between a·g and b.
    let dirs = sample_dirs();
    let sb = frame_samples(b, &dirs);
    let mut best = 0usize;
    let mut best_d = f64::INFINITY;
    for (gi, &g) in group.iter().enumerate() {
        let sa = frame_samples(a.mul(g).normalize(), &dirs);
        let d: f64 = sa.iter().zip(&sb).map(|(x, y)| (x - y) * (x - y)).sum();
        if d < best_d {
            best_d = d;
            best = gi;
        }
    }
    best
}

/// SINGULARITY EXTRACTION: for every interior lattice edge (along z,
/// say), compose the four matchings around the surrounding cells; a
/// non-identity holonomy marks a singular edge. Returns singular-edge
/// coordinates per axis.
#[must_use]
pub fn singular_edges(field: &FrameField) -> Vec<(usize, usize, usize, u8)> {
    let group = cube_group();
    let [nx, ny, nz] = field.dims;
    let mut singular = Vec::new();
    // z-edges: loop over the 4 cells around (i, j, *) plaquettes.
    for k in 0..nz {
        for j in 0..ny.saturating_sub(1) {
            for i in 0..nx.saturating_sub(1) {
                let c = [
                    idx(field.dims, i, j, k),
                    idx(field.dims, i + 1, j, k),
                    idx(field.dims, i + 1, j + 1, k),
                    idx(field.dims, i, j + 1, k),
                ];
                // Compose matchings around the loop.
                let mut hol = Quat::identity();
                let mut ok = true;
                for e in 0..4 {
                    let a = field.frames[c[e]];
                    let b = field.frames[c[(e + 1) % 4]];
                    let g = group[matching(a, b, &group)];
                    hol = hol.mul(g).normalize();
                    let _ = ok;
                    ok = true;
                }
                // Identity up to sign?
                let is_id = (hol.w.abs() - 1.0).abs() < 1e-6;
                if !is_id {
                    singular.push((i, j, k, 2u8));
                }
            }
        }
    }
    singular
}

/// The hex-dominant extraction verdict.
#[derive(Debug, Clone, PartialEq)]
pub struct HexMesh {
    /// Hexes as lattice cells kept.
    pub hexes: usize,
    /// Transition elements (boundary-clipped cells: prisms/tets class).
    pub transitions: usize,
    /// Hex-dominance fraction.
    pub hex_fraction: f64,
    /// Minimum scaled Jacobian over hexes.
    pub min_scaled_jacobian: f64,
    /// Which route produced it.
    pub route: Route,
    /// The explanatory diagnostic when the fallback (or refusal) fires.
    pub diagnostic: String,
}

/// Which meshing route ran.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Route {
    /// The frame field was integrable (singularity-free, axis-class).
    FrameField,
    /// Polycube fallback (documented decision).
    Polycube,
    /// Refused: routed to IGA/CutFEM (the honest-alternatives doctrine).
    RoutedToAlternatives,
}

/// Extract a hex-dominant mesh for a box-like domain described by an
/// inside predicate on cell centers. DECISION CRITERIA (documented):
/// an empty singular set AND low frame-field energy → the frame-field
/// route (on the axis-aligned lattice this IS the polycube grid); a
/// non-empty singular set → the POLYCUBE fallback (labels snapped to
/// axes); a fallback whose hex fraction misses the floor → refusal
/// with the IGA/CutFEM diagnostic.
#[must_use]
pub fn extract_hex_dominant(
    field: &FrameField,
    inside: &dyn Fn(f64, f64, f64) -> bool,
    hex_floor: f64,
) -> HexMesh {
    let [nx, ny, nz] = field.dims;
    let singular = singular_edges(field);
    let energy = dirichlet_energy(field);
    #[allow(clippy::cast_precision_loss)]
    let per_pair = energy / ((nx * ny * nz) as f64).max(1.0);
    let route = if singular.is_empty() && per_pair < 0.5 {
        Route::FrameField
    } else {
        Route::Polycube
    };
    // Both routes rasterize the axis grid (the frame-field route's
    // parameterization IS axis-aligned when singularity-free on the
    // box lattice; the polycube route snaps labels to axes — identical
    // rasterization, different justification; CONTRACT documents it).
    let mut hexes = 0usize;
    let mut transitions = 0usize;
    for k in 0..nz {
        for j in 0..ny {
            for i in 0..nx {
                #[allow(clippy::cast_precision_loss)]
                let (x, y, z) = (
                    (i as f64 + 0.5) / nx as f64,
                    (j as f64 + 0.5) / ny as f64,
                    (k as f64 + 0.5) / nz as f64,
                );
                if inside(x, y, z) {
                    // Full cell inside? Probe corners.
                    #[allow(clippy::cast_precision_loss)]
                    let corners_in = (0..8)
                        .filter(|c| {
                            let (dx, dy, dz) = (
                                f64::from(c & 1),
                                f64::from((c >> 1) & 1),
                                f64::from((c >> 2) & 1),
                            );
                            inside(
                                (i as f64 + dx) / nx as f64,
                                (j as f64 + dy) / ny as f64,
                                (k as f64 + dz) / nz as f64,
                            )
                        })
                        .count();
                    if corners_in == 8 {
                        hexes += 1;
                    } else {
                        transitions += 1;
                    }
                }
            }
        }
    }
    let total = hexes + transitions;
    #[allow(clippy::cast_precision_loss)]
    let hex_fraction = if total == 0 {
        0.0
    } else {
        hexes as f64 / total as f64
    };
    // Axis-aligned lattice hexes have scaled Jacobian exactly 1.
    let min_scaled_jacobian = if hexes > 0 { 1.0 } else { 0.0 };
    if hex_fraction < hex_floor {
        return HexMesh {
            hexes,
            transitions,
            hex_fraction,
            min_scaled_jacobian,
            route: Route::RoutedToAlternatives,
            diagnostic: format!(
                "hex-dominance {hex_fraction:.2} misses the {hex_floor:.2} floor on this \
                 geometry; use IGA or CutFEM instead — they cover this case at higher \
                 accuracy (the honest-alternatives doctrine)"
            ),
        };
    }
    HexMesh {
        hexes,
        transitions,
        hex_fraction,
        min_scaled_jacobian,
        route,
        diagnostic: match route {
            Route::FrameField => "frame field integrable: singularity-free, low energy".into(),
            Route::Polycube => format!(
                "polycube fallback: {} singular edges or high energy ({per_pair:.3}/cell)",
                singular.len()
            ),
            Route::RoutedToAlternatives => unreachable!(),
        },
    }
}

/// The HONESTY HARNESS: interpolation accuracy-per-DOF, trilinear hex
/// lattice vs linear-tet split of the same lattice, on a smooth field.
/// Returns (hex L2 error, tet L2 error) at MATCHED node count — the
/// caller reports whichever wins, honestly.
#[must_use]
pub fn accuracy_per_dof(n: usize) -> (f64, f64) {
    let f = |x: f64, y: f64, z: f64| (2.0 * x).sin() * (1.5 * y).cos() * (z * z);
    #[allow(clippy::cast_precision_loss)]
    let h = 1.0 / n as f64;
    // Sample error at cell-interior probe points.
    let mut hex_err = 0.0f64;
    let mut tet_err = 0.0f64;
    let mut count = 0usize;
    for k in 0..n {
        for j in 0..n {
            for i in 0..n {
                #[allow(clippy::cast_precision_loss)]
                let (x0, y0, z0) = (i as f64 * h, j as f64 * h, k as f64 * h);
                // Probe at an asymmetric interior point.
                let (px, py, pz) = (x0 + 0.37 * h, y0 + 0.61 * h, z0 + 0.23 * h);
                let truth = f(px, py, pz);
                // Trilinear from the 8 corners.
                let mut tri = 0.0f64;
                for c in 0..8 {
                    let (dx, dy, dz) = (
                        f64::from(c & 1),
                        f64::from((c >> 1) & 1),
                        f64::from((c >> 2) & 1),
                    );
                    let w = (if c & 1 == 1 { 0.37 } else { 0.63 })
                        * (if (c >> 1) & 1 == 1 { 0.61 } else { 0.39 })
                        * (if (c >> 2) & 1 == 1 { 0.23 } else { 0.77 });
                    tri += w * f(x0 + dx * h, y0 + dy * h, z0 + dz * h);
                }
                // Linear tet: the probe's containing tet in the 6-tet
                // split — approximate with the linear interpolant from
                // the cell's main diagonal tet (v0, vx, vy, vz): exact
                // barycentric on that tet.
                let (l1, l2, l3) = (0.37, 0.61, 0.23);
                let l0 = 1.0 - l1 - l2 - l3;
                let lin = if l0 >= 0.0 {
                    l0 * f(x0, y0, z0)
                        + l1 * f(x0 + h, y0, z0)
                        + l2 * f(x0, y0 + h, z0)
                        + l3 * f(x0, y0, z0 + h)
                } else {
                    // Falls in the complementary tet: interpolate from
                    // the far corner.
                    let (m1, m2, m3) = (1.0 - l1, 1.0 - l2, 1.0 - l3);
                    let m0 = 1.0 - m1 - m2 - m3;
                    m0 * f(x0 + h, y0 + h, z0 + h)
                        + m1 * f(x0, y0 + h, z0 + h)
                        + m2 * f(x0 + h, y0, z0 + h)
                        + m3 * f(x0 + h, y0 + h, z0)
                };
                hex_err += (tri - truth).powi(2);
                tet_err += (lin - truth).powi(2);
                count += 1;
            }
        }
    }
    #[allow(clippy::cast_precision_loss)]
    {
        (
            f64::sqrt(hex_err / count as f64),
            f64::sqrt(tet_err / count as f64),
        )
    }
}
