//! Payne–Hanek argument reduction (bead r6r5): extends sin/cos/tan
//! beyond `TRIG_DOMAIN` = 2²⁰ to ALL finite f64. The engine is 1280
//! bits of 2/π stored as u64 limbs; the reduction multiplies the
//! argument's mantissa against a windowed slice of those limbs with
//! exact u64 widening arithmetic, keeps the quadrant bits and 254
//! fraction bits (mod-4 wrapping — whole multiples of 4 quadrants
//! cannot matter), and converts the fraction to a double-double times
//! π/2 for the existing polynomial cores.
//!
//! SELF-VERIFYING CONSTANTS: the limbs are hardcoded AND regenerated
//! at test time by an all-integer Machin bignum (π = 16·atan(1/5) −
//! 4·atan(1/239) in u64-limb fixed point, then binary long division
//! for 2/π) — no hand transcription is trusted; the regeneration test
//! recomputes every limb from integer arithmetic (G5: bit-identical
//! on every ISA by construction).

use crate::dd::Dd;

/// Number of shipped 2/π fraction limbs (1280 bits).
pub const PH_LIMBS: usize = 20;

/// 2/π as pure-fraction u64 limbs: 2/π = Σ LIMBS[i]·2^(−64(i+1)).
/// Generated by [`generate_two_over_pi`]; the battery regenerates and
/// compares every limb.
pub const TWO_OVER_PI_LIMBS: [u64; PH_LIMBS] = [
    0xA2F9_836E_4E44_1529,
    0xFC27_57D1_F534_DDC0,
    0xDB62_9599_3C43_9041,
    0xFE51_63AB_DEBB_C561,
    0xB724_6E3A_424D_D2E0,
    0x0649_2EEA_09D1_921C,
    0xFE1D_EB1C_B129_A73E,
    0xE882_35F5_2EBB_4484,
    0xE99C_7026_B45F_7E41,
    0x3991_D639_8353_39F4,
    0x9C84_5F8B_BDF9_283B,
    0x1FF8_97FF_DE05_980F,
    0xEF2F_118B_5A0A_6D1F,
    0x6D36_7ECF_27CB_09B7,
    0x4F46_3F66_9E5F_EA2D,
    0x7527_BAC7_EBE5_F17B,
    0x3D07_39F7_8A52_92EA,
    0x6BFB_5FB1_1F8D_5D08,
    0x5603_3046_FC7B_6BAB,
    0xF0CF_BC20_9AF4_361D,
];

/// π/2 as a double-double (hi is the correctly rounded f64; lo the
/// residual — carries the value to ~2^−107).
const PIO2_DD: Dd = Dd {
    hi: std::f64::consts::FRAC_PI_2,
    lo: 6.123_233_995_736_766e-17,
};

// ---------------------------------------------------------------------
// All-integer fixed-point bignum (generator + reference machinery).
// Value = int + Σ frac[i]·2^(−64(i+1)). Deterministic by construction.
// ---------------------------------------------------------------------

/// Fixed-point non-negative bignum for the constant generator.
#[derive(Clone, PartialEq, Eq, Debug)]
pub struct Fx {
    /// Integer part.
    pub int: u64,
    /// Fraction limbs, most significant first.
    pub frac: Vec<u64>,
}

impl Fx {
    /// Zero with `n` fraction limbs.
    #[must_use]
    pub fn zero(n: usize) -> Fx {
        Fx {
            int: 0,
            frac: vec![0; n],
        }
    }

    /// Divide in place by a small integer (school division, high to
    /// low, u128 intermediates — exact truncation toward zero).
    pub fn div_small(&mut self, d: u64) {
        let mut rem: u64 = self.int % d;
        self.int /= d;
        for limb in &mut self.frac {
            let acc = (u128::from(rem) << 64) | u128::from(*limb);
            *limb = (acc / u128::from(d)) as u64;
            rem = (acc % u128::from(d)) as u64;
        }
    }

    /// Multiply in place by a small integer (low to high with carry).
    ///
    /// # Panics
    /// If the integer part overflows u64 (generator contract — the
    /// constants involved stay tiny).
    pub fn mul_small(&mut self, m: u64) {
        let mut carry: u64 = 0;
        for limb in self.frac.iter_mut().rev() {
            let acc = u128::from(*limb) * u128::from(m) + u128::from(carry);
            *limb = acc as u64;
            carry = (acc >> 64) as u64;
        }
        let acc = u128::from(self.int) * u128::from(m) + u128::from(carry);
        assert!(acc >> 64 == 0, "Fx integer overflow in mul_small");
        self.int = acc as u64;
    }

    /// self += o (matching limb counts).
    pub fn add_assign(&mut self, o: &Fx) {
        let mut carry: u64 = 0;
        for (a, b) in self.frac.iter_mut().rev().zip(o.frac.iter().rev()) {
            let acc = u128::from(*a) + u128::from(*b) + u128::from(carry);
            *a = acc as u64;
            carry = (acc >> 64) as u64;
        }
        self.int = self.int + o.int + carry;
    }

    /// self −= o (requires self ≥ o; matching limb counts).
    pub fn sub_assign(&mut self, o: &Fx) {
        let mut borrow: u64 = 0;
        for (a, b) in self.frac.iter_mut().rev().zip(o.frac.iter().rev()) {
            let (d1, b1) = a.overflowing_sub(*b);
            let (d2, b2) = d1.overflowing_sub(borrow);
            *a = d2;
            borrow = u64::from(b1) + u64::from(b2);
        }
        self.int = self.int - o.int - borrow;
    }

    /// self ≥ o?
    #[must_use]
    pub fn ge(&self, o: &Fx) -> bool {
        if self.int != o.int {
            return self.int > o.int;
        }
        for (a, b) in self.frac.iter().zip(&o.frac) {
            if a != b {
                return a > b;
            }
        }
        true
    }

    /// All limbs zero?
    #[must_use]
    pub fn is_zero(&self) -> bool {
        self.int == 0 && self.frac.iter().all(|&l| l == 0)
    }
}

/// atan(1/n) by the alternating Gregory series, all-integer.
#[must_use]
pub fn atan_recip(n: u64, limbs: usize) -> Fx {
    let mut term = Fx::zero(limbs);
    term.int = 1;
    term.div_small(n); // 1/n
    let mut sum = term.clone();
    let n2 = n * n;
    let mut k: u64 = 1;
    let mut power = term;
    loop {
        power.div_small(n2);
        if power.is_zero() {
            break;
        }
        let mut t = power.clone();
        t.div_small(2 * k + 1);
        if k.is_multiple_of(2) {
            sum.add_assign(&t);
        } else {
            sum.sub_assign(&t);
        }
        k += 1;
    }
    sum
}

/// π by Machin's formula, all-integer.
#[must_use]
pub fn generate_pi(limbs: usize) -> Fx {
    let mut a = atan_recip(5, limbs);
    a.mul_small(16);
    let mut b = atan_recip(239, limbs);
    b.mul_small(4);
    a.sub_assign(&b);
    a
}

/// 2/π limbs by binary long division against the Machin π
/// (guard limbs beyond `out_limbs` make the shipped limbs exact).
#[must_use]
pub fn generate_two_over_pi(out_limbs: usize) -> Vec<u64> {
    let guard = out_limbs + 4;
    let pi = generate_pi(guard);
    let mut rem = Fx::zero(guard);
    rem.int = 2;
    let mut out = vec![0u64; out_limbs];
    for limb_out in &mut out {
        let mut word: u64 = 0;
        for _ in 0..64 {
            rem.mul_small(2);
            word <<= 1;
            if rem.ge(&pi) {
                rem.sub_assign(&pi);
                word |= 1;
            }
        }
        *limb_out = word;
    }
    out
}

// ---------------------------------------------------------------------
// The reduction.
// ---------------------------------------------------------------------

/// Payne–Hanek reduction of any finite x with |x| > 1: returns the
/// reduced argument r ∈ [−π/4, π/4] (as the rounded double of a
/// double-double product) and the quadrant of x modulo 2π.
///
/// # Panics
/// On non-finite input (callers gate NaN/∞ first — det.rs contract).
#[must_use]
pub fn reduce_pio2_large(x: f64) -> (f64, u8) {
    assert!(x.is_finite(), "Payne-Hanek requires finite input");
    let neg = x < 0.0;
    let bits = x.abs().to_bits();
    let e = i64::try_from((bits >> 52) & 0x7FF).expect("11-bit field") - 1023;
    let m = (bits & ((1u64 << 52) - 1)) | (1u64 << 52); // 53-bit mantissa
    let s = e - 52; // x = m · 2^s
    // 256-bit accumulator, little-endian limbs; bit index i (0..256)
    // carries weight 2^(i − 254): bits 255..254 are the quadrant
    // (weights 2^1, 2^0), the rest the fraction of (x·2/π) mod 4.
    let mut acc = [0u64; 4];
    for (i, &limb) in TWO_OVER_PI_LIMBS.iter().enumerate() {
        // Term m·L_i with LSB weight 2^(s − 64(i+1)) → LSB accumulator
        // bit index:
        let idx = s - 64 * (i64::try_from(i).expect("small index") + 1) + 254;
        if idx >= 256 {
            continue; // whole multiple of 4 quadrants — drops out mod 4
        }
        if idx <= -118 {
            continue; // entirely below the accumulator floor
        }
        let prod = u128::from(m) * u128::from(limb);
        add_shifted(&mut acc, prod, idx);
    }
    // Quadrant bits and 254-bit fraction.
    let mut q = (acc[3] >> 62) as u8 & 3;
    // Fraction as the top 128 bits after the quadrant (weights 2^-1 …).
    let f_hi = (acc[3] << 2) | (acc[2] >> 62);
    let f_lo = (acc[2] << 2) | (acc[1] >> 62);
    let (frac_hi, frac_lo, negate) = if f_hi >> 63 == 1 {
        // f ≥ ½: round the quadrant up, take the negative complement
        // (r = (f − 1)·π/2 ∈ [−π/4, 0)).
        q = (q + 1) & 3;
        let lo = (!f_lo).wrapping_add(1);
        let hi = if lo == 0 {
            (!f_hi).wrapping_add(1)
        } else {
            !f_hi
        };
        (hi, lo, true)
    } else {
        (f_hi, f_lo, false)
    };
    // f as a double-double via EXACT 53-bit splits (a raw u64→f64
    // cast would round away 11 low bits that the lo limb cannot
    // recover): a·2^−53 + b·2^−106, both parts exact.
    let a = frac_hi >> 11;
    let b = ((frac_hi & 0x7FF) << 42) | (frac_lo >> 22);
    #[allow(clippy::cast_precision_loss)] // both fit in 53 bits — exact
    let fd = Dd::from_pair(
        (a as f64) * 2.0f64.powi(-53),  // det-ok: base 2, exact (4xnt)
        (b as f64) * 2.0f64.powi(-106), // det-ok: base 2, exact (4xnt)
    );
    let r = fd * PIO2_DD;
    let r_signed = if negate { -r.to_f64() } else { r.to_f64() };
    if neg {
        // Odd symmetry of the reduction: −x·(2/π) = −(4k + q + φ),
        // so the quadrant mirrors mod 4 and the remainder negates.
        (((4 - q) & 3, -r_signed).1, (4 - q) & 3)
    } else {
        (r_signed, q)
    }
}

/// Add `prod` (128 bits) shifted so its LSB sits at accumulator bit
/// `idx` (may be negative: low bits truncate; high bits past 255
/// wrap off — mod-4 semantics).
fn add_shifted(acc: &mut [u64; 4], prod: u128, idx: i64) {
    // Normalize to a non-negative shift by pre-truncating low bits.
    let (val, base) = if idx < 0 {
        let sh = u32::try_from(-idx).expect("bounded shift");
        if sh >= 128 {
            return;
        }
        (prod >> sh, 0u32)
    } else {
        (prod, u32::try_from(idx).expect("bounded index"))
    };
    if val == 0 {
        return;
    }
    let limb = (base / 64) as usize;
    let shift = base % 64;
    // val << shift as a 192-bit value: low 128 bits plus the overflow
    // word (val's top `shift` bits).
    let low128 = val << shift;
    let over = if shift == 0 {
        0u64
    } else {
        (val >> (128 - shift)) as u64
    };
    let parts = [low128 as u64, (low128 >> 64) as u64, over];
    let mut carry = 0u64;
    for (k, &p) in parts.iter().enumerate() {
        let t = limb + k;
        if t >= 4 {
            break;
        }
        let (s1, c1) = acc[t].overflowing_add(p);
        let (s2, c2) = s1.overflowing_add(carry);
        acc[t] = s2;
        carry = u64::from(c1) + u64::from(c2);
    }
    let mut t = limb + 3;
    while carry > 0 && t < 4 {
        let (s, c) = acc[t].overflowing_add(carry);
        acc[t] = s;
        carry = u64::from(c);
        t += 1;
    }
}
