//! G0/G3/G4 admission coverage for fallible BIPOP construction (7tv.23.2).
//!
//! This tranche proves callback-free raw-input refusal, conservative checked
//! seed admission, exact one-callback budget behavior, and replay equivalence
//! between the typed target surface and the legacy compatibility spelling. It
//! also contains any non-finite decision coordinate generated by this BIPOP
//! path before the affected callback.
//! It does not claim objective-output fault containment, cancellation,
//! resumable state, allocation recovery, or authenticated root-input identity.

#![deny(unsafe_code)]

use fs_dfo::{
    BIPOP_ADMISSION_SCHEMA_VERSION, BipopError, BipopReport, BipopRestartRecord, CmaReport,
    CmaStopReason, admit_bipop, bipop_cmaes, try_bipop_cmaes,
};
use fs_la::eigen::{JacobiEighAdmissionError, MAX_EIGEN_WORK_ELEMENTS};
use fs_rand::{STREAM_SEMANTICS_VERSION, StreamKey};
use std::cell::{Cell, RefCell};
use std::panic::{AssertUnwindSafe, catch_unwind};

const ROOT_SEED: u64 = 0xB1_90_00_02;
const RESTART_SEED_STRIDE: u64 = 0x9E37_79B9;

fn sphere(point: &[f64]) -> f64 {
    point.iter().map(|coordinate| coordinate * coordinate).sum()
}

fn assert_slice_bits(left: &[f64], right: &[f64]) {
    assert_eq!(left.len(), right.len());
    for (left, right) in left.iter().zip(right) {
        assert_eq!(left.to_bits(), right.to_bits());
    }
}

fn assert_report_bits(left: &CmaReport, right: &CmaReport) {
    assert_slice_bits(&left.x_best, &right.x_best);
    assert_eq!(left.f_best.to_bits(), right.f_best.to_bits());
    assert_eq!(left.evals, right.evals);
    assert_eq!(left.generations, right.generations);
    assert_eq!(left.converged, right.converged);
    assert_eq!(left.sigma.to_bits(), right.sigma.to_bits());
}

fn assert_record_bits(left: &BipopRestartRecord, right: &BipopRestartRecord) {
    assert_eq!(left.schema_version(), right.schema_version());
    assert_eq!(left.ordinal(), right.ordinal());
    assert_eq!(left.lane(), right.lane());
    assert_eq!(left.lambda(), right.lambda());
    assert_eq!(left.allocated_budget(), right.allocated_budget());
    assert_eq!(left.seed(), right.seed());
    assert_slice_bits(left.start(), right.start());
    assert_eq!(left.trace_start(), right.trace_start());
    assert_eq!(left.trace_end(), right.trace_end());
    assert_eq!(left.stop_reason(), right.stop_reason());
    assert_report_bits(left.report(), right.report());
}

fn assert_bipop_bits(left: &BipopReport, right: &BipopReport) {
    assert_report_bits(&left.best, &right.best);
    assert_eq!(left.schedule, right.schedule);
    assert_eq!(left.total_evals, right.total_evals);
    assert_eq!(left.total_budget(), right.total_budget());
    assert_eq!(left.best_restart(), right.best_restart());
    assert_eq!(left.records().len(), right.records().len());
    for (left, right) in left.records().iter().zip(right.records()) {
        assert_record_bits(left, right);
    }
}

/// G0/G4: malformed raw inputs refuse before the objective sees any point.
#[test]
fn malformed_inputs_and_zero_budget_are_callback_free() {
    let calls = Cell::new(0usize);
    let mut objective = |_point: &[f64]| {
        calls.set(calls.get() + 1);
        0.0
    };

    let error = try_bipop_cmaes(&mut objective, &[], 0.5, 1, None, ROOT_SEED)
        .expect_err("empty start must refuse");
    assert_eq!(error, BipopError::EmptyStart);

    let payload_nan = f64::from_bits(0x7ff8_0000_0000_0042);
    let error = try_bipop_cmaes(&mut objective, &[1.0, payload_nan], 0.5, 1, None, ROOT_SEED)
        .expect_err("non-finite start must refuse");
    assert_eq!(
        error,
        BipopError::NonFiniteStart {
            component: 1,
            bits: payload_nan.to_bits(),
        }
    );

    for sigma in [-0.0, 0.0, f64::INFINITY, f64::NAN] {
        let error = try_bipop_cmaes(&mut objective, &[1.0], sigma, 1, None, ROOT_SEED)
            .expect_err("invalid sigma must refuse");
        assert_eq!(
            error,
            BipopError::InvalidSigma {
                bits: sigma.to_bits(),
            }
        );
    }

    for target in [f64::NEG_INFINITY, f64::INFINITY, payload_nan] {
        let error = try_bipop_cmaes(&mut objective, &[1.0], 0.5, 1, Some(target), ROOT_SEED)
            .expect_err("explicit non-finite target must refuse");
        assert_eq!(
            error,
            BipopError::NonFiniteTarget {
                bits: target.to_bits(),
            }
        );
    }

    let error = try_bipop_cmaes(&mut objective, &[1.0], 0.5, 0, None, ROOT_SEED)
        .expect_err("zero budget must refuse");
    assert_eq!(error, BipopError::ZeroBudget);

    let legacy_panic = catch_unwind(AssertUnwindSafe(|| {
        bipop_cmaes(&mut objective, &[1.0], 0.5, 1, f64::INFINITY, ROOT_SEED)
    }));
    assert!(
        legacy_panic.is_err(),
        "the legacy projection must panic on a typed refusal"
    );

    let overflow_seed = u64::MAX - RESTART_SEED_STRIDE + 1;
    let error = try_bipop_cmaes(&mut objective, &[1.0], 0.5, 2, None, overflow_seed)
        .expect_err("conservative seed overflow must refuse");
    assert_eq!(
        error,
        BipopError::SeedRangeOverflow {
            seed: overflow_seed,
            max_restart_ordinal: 1,
        }
    );
    assert_eq!(calls.get(), 0, "no refused input may invoke the objective");
}

/// G0/G4: BIPOP consumes fs-la's typed Jacobi capability authority before the
/// first callback. Dimension 4096 is representable and cheap to describe, but
/// exceeds that kernel's aggregate-work cap by exactly one boundary step.
#[test]
fn dependency_capability_refusal_is_callback_free_and_exact() {
    let calls = Cell::new(0usize);
    let mut objective = |_point: &[f64]| {
        calls.set(calls.get() + 1);
        0.0
    };
    let x0 = vec![0.0; 4_096];
    let error = try_bipop_cmaes(&mut objective, &x0, 0.5, 29, None, ROOT_SEED)
        .expect_err("dimension 4096 exceeds the shared Jacobi authority");
    assert_eq!(
        error,
        BipopError::EigensolverAdmission {
            error: JacobiEighAdmissionError::WorkCapExceeded {
                dimension: 4_096,
                required_elements: 67_121_152,
                cap_elements: MAX_EIGEN_WORK_ELEMENTS,
            },
        }
    );
    assert_eq!(calls.get(), 0, "dependency refusal must precede callbacks");
}

/// G0: admission exposes deterministic checked maxima and refuses the first
/// root seed whose conservative second-restart coordinate would wrap.
#[test]
fn admission_and_seed_boundary_are_exact() {
    let boundary_seed = u64::MAX - RESTART_SEED_STRIDE;
    let admitted = admit_bipop(&[2.0, -1.0], 0.75, 2, None, boundary_seed)
        .expect("the exact seed boundary admits");
    assert_eq!(BIPOP_ADMISSION_SCHEMA_VERSION, 3);
    assert_eq!(admitted.schema_version(), BIPOP_ADMISSION_SCHEMA_VERSION);
    assert_eq!(
        admitted.stream_semantics_version(),
        STREAM_SEMANTICS_VERSION
    );
    assert_eq!(
        admitted.jacobi_admission(),
        None,
        "budget two cannot reach one base-population generation"
    );
    assert_eq!(admitted.dimension(), 2);
    assert_eq!(admitted.total_budget(), 2);
    assert_eq!(admitted.base_lambda(), 6);
    assert_eq!(admitted.max_large_lambda(), 12);
    assert_eq!(admitted.max_local_budget(), 3_000);
    assert_eq!(admitted.max_restart_ordinal(), 1);
    assert_eq!(admitted.max_matrix_entries(), 4);
    assert_eq!(admitted.max_population_entries(), 24);
    assert_eq!(admitted.max_restart_stream_blocks(), 4);
    assert_eq!(admitted.max_cma_stream_blocks(), 0);

    let overflow_seed = boundary_seed + 1;
    assert_eq!(
        admit_bipop(&[2.0, -1.0], 0.75, 2, None, overflow_seed)
            .expect_err("the next root seed must refuse"),
        BipopError::SeedRangeOverflow {
            seed: overflow_seed,
            max_restart_ordinal: 1,
        }
    );

    let one = admit_bipop(&[2.0, -1.0], 0.75, 1, None, u64::MAX)
        .expect("budget one never derives a second seed");
    assert_eq!(one.max_restart_ordinal(), 0);
    assert_eq!(one.max_large_lambda(), one.base_lambda());
}

/// G0: dependency receipts are reachability-sensitive. For dimension 4096 the
/// final callback-only budget admits because no Jacobi call is possible; the
/// first budget that can fund one complete base population refuses through the
/// shared fs-la authority.
#[test]
fn jacobi_capability_is_required_at_the_first_reachable_generation() {
    let x0 = vec![0.0; 4_096];
    let callback_only = admit_bipop(&x0, 0.5, 28, None, ROOT_SEED)
        .expect("base lambda 28 leaves no complete generation under budget 28");
    assert_eq!(callback_only.base_lambda(), 28);
    assert_eq!(callback_only.jacobi_admission(), None);

    assert!(matches!(
        admit_bipop(&x0, 0.5, 29, None, ROOT_SEED),
        Err(BipopError::EigensolverAdmission {
            error: JacobiEighAdmissionError::WorkCapExceeded {
                dimension: 4_096,
                ..
            }
        })
    ));
}

/// G0: the scheduler theorem, rather than an unbounded `total_budget - 1`
/// surrogate, controls seed and restart-stream admission. Rung eight terminates
/// production and cannot finance a later small restart. Rungs zero through
/// seven contribute scale sum 255, and a full `250*lambda` local cap spends at
/// most `1 + 249*lambda` callbacks. Every continuing non-tail small run spends
/// at least `base_lambda + 1`; only the final `base_lambda` aggregate callbacks
/// can finance one-callback small tails.
#[test]
fn scheduler_bound_avoids_false_large_budget_refusal() {
    const BASE_LAMBDA: u64 = 6;
    const PRE_TERMINAL_LARGE_SCALE_SUM: u64 = 255;
    const PRE_TERMINAL_LARGE_SPEND: u64 = 8 + BASE_LAMBDA * 249 * PRE_TERMINAL_LARGE_SCALE_SUM;
    const CONTINUING_SMALL_SPEND: u64 = BASE_LAMBDA + 1;
    const MAX_FULL_GENERATION_SMALL_RUNS: u64 =
        PRE_TERMINAL_LARGE_SPEND.div_ceil(CONTINUING_SMALL_SPEND);
    const MAX_ORDINAL: u64 = 8 + MAX_FULL_GENERATION_SMALL_RUNS + BASE_LAMBDA;

    let seed_delta = MAX_ORDINAL
        .checked_mul(RESTART_SEED_STRIDE)
        .expect("the theorem fixture fits u64");
    let boundary_seed = u64::MAX - seed_delta;
    let admitted = admit_bipop(&[2.0, -1.0], 0.75, usize::MAX, None, boundary_seed)
        .expect("scheduler-aware boundary must admit despite the enormous budget");

    assert_eq!(admitted.max_restart_ordinal(), MAX_ORDINAL);
    assert_eq!(MAX_ORDINAL, 54_440);
    assert_eq!(admitted.max_large_lambda(), 1_536);
    assert_eq!(admitted.max_local_budget(), 384_000);
    assert_eq!(admitted.max_population_entries(), 3_072);
    assert_eq!(
        admitted.max_restart_stream_blocks(),
        2 * 2 * u128::from(MAX_ORDINAL)
    );
    assert_eq!(admitted.max_cma_stream_blocks(), 1_529_856);

    assert_eq!(
        admit_bipop(&[2.0, -1.0], 0.75, usize::MAX, None, boundary_seed + 1)
            .expect_err("the first seed beyond the theorem boundary must refuse"),
        BipopError::SeedRangeOverflow {
            seed: boundary_seed + 1,
            max_restart_ordinal: MAX_ORDINAL,
        }
    );
}

/// G0/G3: the admission theorem is coupled to fs-rand's live stream
/// advancement, not only to a duplicated factor-of-two arithmetic KAT.
#[test]
fn admission_binds_live_normal_counter_consumption() {
    let admitted = admit_bipop(&[1.0], 0.5, 5, None, ROOT_SEED).expect("fixture admits");
    let mut stream = StreamKey {
        seed: ROOT_SEED,
        kernel: 0xD1F0,
        tile: 0,
    }
    .stream();
    assert_eq!(stream.index(), 0);
    let _ = stream.next_normal();
    assert_eq!(
        stream.index(),
        2,
        "one strict normal must consume two blocks"
    );
    assert_eq!(
        admitted.stream_semantics_version(),
        STREAM_SEMANTICS_VERSION
    );
}

/// G0/G4: one admitted callback is a complete final partial restart, not a
/// hidden population overshoot or an empty report.
#[test]
fn one_callback_budget_is_exact_and_replayable() {
    let x0 = [2.0, -1.0];
    let seen = RefCell::new(Vec::<Vec<u64>>::new());
    let mut objective = |point: &[f64]| {
        seen.borrow_mut()
            .push(point.iter().map(|value| value.to_bits()).collect());
        sphere(point)
    };
    let report =
        try_bipop_cmaes(&mut objective, &x0, 0.75, 1, None, u64::MAX).expect("one callback admits");
    report
        .validate_ledger()
        .expect("generated ledger validates");

    assert_eq!(seen.borrow().as_slice(), &[x0.map(f64::to_bits).to_vec()]);
    assert_eq!(report.total_evals, 1);
    assert_eq!(report.total_budget(), 1);
    assert_eq!(report.records().len(), 1);
    assert_eq!(report.best_restart(), 0);
    let record = &report.records()[0];
    assert_eq!(record.ordinal(), 0);
    assert_eq!(record.allocated_budget(), 1);
    assert_eq!((record.trace_start(), record.trace_end()), (0, 1));
    assert_eq!(record.stop_reason(), CmaStopReason::BudgetExhausted);
    assert_eq!(record.report().evals, 1);
    assert_eq!(record.report().generations, 0);
    assert!(!record.report().converged);
    assert_slice_bits(record.start(), &x0);
}

/// G0/G4: a finite extreme root and sigma can overflow a generated CMA query.
/// The initial finite point may have been observed, but the first malformed
/// candidate is refused with exact causal coordinates and never reaches user
/// code.
#[test]
fn generated_nonfinite_candidate_is_contained_before_callback() {
    let calls = Cell::new(0usize);
    let mut objective = |point: &[f64]| {
        assert!(
            point.iter().all(|value| value.is_finite()),
            "the checked surface must never expose a non-finite decision coordinate"
        );
        calls.set(calls.get() + 1);
        0.0
    };

    let error = try_bipop_cmaes(&mut objective, &[f64::MAX], f64::MAX, 5, None, ROOT_SEED)
        .expect_err("the first generated candidate overflows at the retained seed");
    assert_eq!(
        calls.get(),
        1,
        "only the finite initial point is observable"
    );
    assert_eq!(
        error,
        BipopError::GeneratedCandidateNonFinite {
            restart: 0,
            generation: 1,
            candidate: 0,
            component: 0,
            bits: f64::INFINITY.to_bits(),
        }
    );
}

/// G0/G4: the shared restart stream is a separate containment boundary from
/// per-restart CMA sampling. A finite root can overflow its perturbed restart;
/// that restart must be refused before its initial callback.
#[test]
fn generated_nonfinite_restart_start_is_contained_before_callback() {
    let calls = Cell::new(0usize);
    let mut objective = |point: &[f64]| {
        assert!(point.iter().all(|value| value.is_finite()));
        calls.set(calls.get() + 1);
        0.0
    };

    let error = try_bipop_cmaes(
        &mut objective,
        &[f64::MAX],
        f64::MAX,
        2,
        None,
        0xB1_90_00_00,
    )
    .expect_err("the retained restart perturbation overflows");
    assert_eq!(calls.get(), 1, "only restart zero may invoke the callback");
    assert_eq!(
        error,
        BipopError::GeneratedStartNonFinite {
            restart: 1,
            component: 0,
            bits: f64::INFINITY.to_bits(),
        }
    );
}

/// G0: `Some(target)` and `None` are behaviorally distinct, not merely two
/// serializations of an infinity sentinel. A target reached at the initial
/// callback stops exactly there; no target consumes the admitted generation.
#[test]
fn typed_target_controls_initial_stop_without_sentinel_ambiguity() {
    let run = |target: Option<f64>| {
        let calls = Cell::new(0usize);
        let mut objective = |_point: &[f64]| {
            calls.set(calls.get() + 1);
            0.0
        };
        let report = try_bipop_cmaes(&mut objective, &[1.0], 0.5, 5, target, ROOT_SEED)
            .expect("target fixture admits");
        (report, calls.get())
    };

    let (targeted, targeted_calls) = run(Some(0.0));
    assert_eq!(targeted_calls, 1);
    assert_eq!(targeted.total_evals, 1);
    assert!(targeted.best.converged);
    assert_eq!(
        targeted.records()[0].stop_reason(),
        CmaStopReason::TargetReached
    );

    let (untargeted, untargeted_calls) = run(None);
    assert_eq!(untargeted_calls, 5);
    assert_eq!(untargeted.total_evals, 5);
    assert!(!untargeted.best.converged);
    assert_eq!(
        untargeted.records()[0].stop_reason(),
        CmaStopReason::BudgetExhausted
    );
}

/// G3/G5-local: the checked target spelling replays every retained bit and is
/// a compatibility projection of both legacy finite and legacy no-target use.
#[test]
fn typed_and_legacy_targets_preserve_complete_report_bits() {
    let x0 = [1.25, -0.75];
    let run_typed = |target: Option<f64>| {
        let mut objective = |point: &[f64]| sphere(point);
        try_bipop_cmaes(&mut objective, &x0, 0.5, 20, target, ROOT_SEED).expect("fixture admits")
    };
    let run_legacy = |target: f64| {
        let mut objective = |point: &[f64]| sphere(point);
        bipop_cmaes(&mut objective, &x0, 0.5, 20, target, ROOT_SEED)
    };

    let finite_first = run_typed(Some(-1.0));
    let finite_replay = run_typed(Some(-1.0));
    let finite_legacy = run_legacy(-1.0);
    assert_bipop_bits(&finite_first, &finite_replay);
    assert_bipop_bits(&finite_first, &finite_legacy);

    let none_first = run_typed(None);
    let none_replay = run_typed(None);
    let none_legacy = run_legacy(f64::NEG_INFINITY);
    assert_bipop_bits(&none_first, &none_replay);
    assert_bipop_bits(&none_first, &none_legacy);
}
