//! GRADIENT CERTIFICATES (addendum Proposal 1, bead bk0o.3; [S], behind
//! the `gradient-certs` feature): gradients are CLAIMS like any other
//! and get COLORS like any other — a gradient without a certificate is
//! folklore. Three pieces:
//!
//! - an outward-rounded DIAGNOSTIC on the sampled adjoint consistency
//!   residual (`⟨Av, w⟩ − ⟨v, Aᵀw⟩`). It checks the registered
//!   transpose implementation at seeded probes; it does not enclose all inputs
//!   and does not prove that the resulting gradient differentiates the stated
//!   objective;
//! - MANDATORY finite-difference spot checks along seeded random
//!   directions via the falsifier registry's `adjoint-gradient` →
//!   `finite-difference-spot-check` pairing (Proposal 6): the
//!   independent cross-check a transpose bug or sign error trips;
//! - the MERGE GATE: no gradient merges without a passing check —
//!   the base plan's CI gradient-gate discipline extended to
//!   seam-crossing, ledger-transposed gradients.

use crate::mitigate::GradientGrade;
use crate::transpose::{FdVerdict, fd_falsifier};
use fs_evidence::{Color, ValidityDomain, color_identity_reason, color_leaf_identity_reason};
use fs_ivl::Interval;

/// Maximum rows admitted by the sampled transpose diagnostic.
pub const MAX_SPARSE_LINEAR_ROWS: usize = 65_536;
/// Maximum columns admitted by the sampled transpose diagnostic.
pub const MAX_SPARSE_LINEAR_COLS: usize = 65_536;
/// Maximum stored entries admitted by the sampled transpose diagnostic.
pub const MAX_SPARSE_LINEAR_ENTRIES: usize = 1_048_576;
/// Maximum seeded transpose probes in one call.
pub const MAX_ADJOINT_RESIDUAL_PROBES: usize = 4_096;
/// Maximum seeded finite-difference directions in one call.
pub const MAX_FD_DIRECTIONS: usize = 4_096;
/// Maximum gradient dimension admitted by the finite-difference helper.
pub const MAX_GRADIENT_DIMENSION: usize = 65_536;
/// Maximum scalar components generated by either probe helper in one call.
pub const MAX_PROBE_COMPONENTS: usize = 1_048_576;
/// Maximum sparse-entry visits admitted by one sampled transpose diagnostic.
///
/// Each probe traverses every stored entry once in the forward apply and once
/// in the transpose apply. This aggregate cap prevents independently valid
/// entry/probe counts from multiplying into an unbounded synchronous scan.
pub const MAX_ADJOINT_RESIDUAL_ENTRY_VISITS: usize = 16_777_216;
/// Maximum axes retained from a caller-declared experimental anchor.
pub const MAX_ANCHOR_AXES: usize = 64;

const MAX_OPERATOR_L1_NORM: f64 = f64::MAX / 64.0;
const ANCHOR_DIAGNOSTIC_DOMAIN: &str = "org.frankensim.fs-adjoint.gradient-anchor-declaration.v1";
const FD_CONTEXT_DOMAIN: &str = "org.frankensim.fs-adjoint.fd-check-context.v1";

/// Invalid or unbounded input to a gradient-certificate diagnostic.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum GradientCertError {
    /// A caller-declared objective identity cannot enter the context digest.
    InvalidObjectiveIdentity {
        /// Shared leaf-identity rejection reason.
        reason: &'static str,
    },
    /// A count must be nonzero and no larger than its public limit.
    InvalidCount {
        /// Which count failed.
        field: &'static str,
        /// Caller-provided count.
        value: usize,
        /// Largest accepted count.
        max: usize,
    },
    /// A sparse operator dimension is empty or exceeds its public limit.
    InvalidSparseShape {
        /// Number of rows.
        rows: usize,
        /// Number of columns.
        cols: usize,
    },
    /// A sparse entry cannot be evaluated safely.
    InvalidSparseEntry {
        /// Row containing the entry.
        row: usize,
        /// Position within the row.
        entry: usize,
        /// Stable actionable reason.
        reason: &'static str,
    },
    /// Two vectors describing the same gradient point have different sizes.
    DimensionMismatch {
        /// Point dimension.
        point: usize,
        /// Gradient dimension.
        gradient: usize,
    },
    /// A point or gradient component is unusable.
    InvalidVectorValue {
        /// `point` or `gradient`.
        field: &'static str,
        /// Component index.
        index: usize,
        /// Stable actionable reason.
        reason: &'static str,
    },
    /// A checked aggregate exceeds the bounded work budget.
    WorkBudgetExceeded {
        /// Diagnostic being bounded.
        operation: &'static str,
        /// Requested work units, or `usize::MAX` on overflow.
        requested: usize,
        /// Largest accepted work-unit count.
        max: usize,
    },
    /// The objective returned a non-finite finite-difference diagnostic.
    InvalidFdVerdict {
        /// Seeded direction index.
        direction: usize,
        /// Non-finite or invalid verdict field.
        field: &'static str,
    },
    /// A finite-difference perturbation is non-finite or rounds back to the
    /// unperturbed coordinate.
    UnrepresentablePerturbation {
        /// Seeded direction index.
        direction: usize,
        /// Coordinate index.
        component: usize,
        /// `coarse-plus`, `coarse-minus`, `fine-plus`, or `fine-minus`.
        step: &'static str,
        /// Stable actionable reason.
        reason: &'static str,
    },
}

impl core::fmt::Display for GradientCertError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::InvalidObjectiveIdentity { reason } => write!(
                f,
                "finite-difference objective identity is unusable: {reason}"
            ),
            Self::InvalidCount { field, value, max } => {
                write!(f, "{field} must be in 1..={max}, got {value}")
            }
            Self::InvalidSparseShape { rows, cols } => write!(
                f,
                "sparse operator shape must be within 1..={MAX_SPARSE_LINEAR_ROWS} rows and \
                 1..={MAX_SPARSE_LINEAR_COLS} columns, got {rows}x{cols}"
            ),
            Self::InvalidSparseEntry { row, entry, reason } => {
                write!(
                    f,
                    "invalid sparse entry at row {row}, offset {entry}: {reason}"
                )
            }
            Self::DimensionMismatch { point, gradient } => write!(
                f,
                "point/gradient dimensions differ: point has {point}, gradient has {gradient}"
            ),
            Self::InvalidVectorValue {
                field,
                index,
                reason,
            } => write!(f, "invalid {field}[{index}]: {reason}"),
            Self::WorkBudgetExceeded {
                operation,
                requested,
                max,
            } => write!(
                f,
                "{operation} requests {requested} work units; maximum is {max}"
            ),
            Self::InvalidFdVerdict { direction, field } => write!(
                f,
                "finite-difference direction {direction} produced invalid {field}"
            ),
            Self::UnrepresentablePerturbation {
                direction,
                component,
                step,
                reason,
            } => write!(
                f,
                "finite-difference direction {direction}, component {component}, {step} \
                 perturbation is unusable: {reason}"
            ),
        }
    }
}

impl std::error::Error for GradientCertError {}

/// A sparse linear operator (rows of `(col, weight)`) with point and
/// INTERVAL applies — the certifiable form of restriction/conversion
/// seams.
#[derive(Debug, Clone)]
pub struct SparseLinear {
    /// Rows of (column, weight).
    pub rows: Vec<Vec<(usize, f64)>>,
    /// Column count.
    pub ncols: usize,
}

impl SparseLinear {
    /// Validate dimensions, storage, indices, and arithmetic inputs before any
    /// allocation or indexed access.
    ///
    /// # Errors
    /// Returns a location-bearing [`GradientCertError`] for malformed input.
    pub fn validate(&self) -> Result<(), GradientCertError> {
        self.validated_entry_count().map(|_| ())
    }

    fn validated_entry_count(&self) -> Result<usize, GradientCertError> {
        if !(1..=MAX_SPARSE_LINEAR_ROWS).contains(&self.rows.len())
            || !(1..=MAX_SPARSE_LINEAR_COLS).contains(&self.ncols)
        {
            return Err(GradientCertError::InvalidSparseShape {
                rows: self.rows.len(),
                cols: self.ncols,
            });
        }
        let mut entries = 0usize;
        let mut l1_norm = 0.0f64;
        for (row_index, row) in self.rows.iter().enumerate() {
            entries =
                entries
                    .checked_add(row.len())
                    .ok_or(GradientCertError::WorkBudgetExceeded {
                        operation: "sparse-entry validation",
                        requested: usize::MAX,
                        max: MAX_SPARSE_LINEAR_ENTRIES,
                    })?;
            if entries > MAX_SPARSE_LINEAR_ENTRIES {
                return Err(GradientCertError::WorkBudgetExceeded {
                    operation: "sparse-entry validation",
                    requested: entries,
                    max: MAX_SPARSE_LINEAR_ENTRIES,
                });
            }
            for (entry_index, &(column, weight)) in row.iter().enumerate() {
                if column >= self.ncols {
                    return Err(GradientCertError::InvalidSparseEntry {
                        row: row_index,
                        entry: entry_index,
                        reason: "column index is outside ncols",
                    });
                }
                if !weight.is_finite() {
                    return Err(GradientCertError::InvalidSparseEntry {
                        row: row_index,
                        entry: entry_index,
                        reason: "weight must be finite",
                    });
                }
                l1_norm += weight.abs();
                if !l1_norm.is_finite() || l1_norm > MAX_OPERATOR_L1_NORM {
                    return Err(GradientCertError::InvalidSparseEntry {
                        row: row_index,
                        entry: entry_index,
                        reason: "operator L1 norm exceeds the safe interval-arithmetic range",
                    });
                }
            }
        }
        Ok(entries)
    }

    fn apply_iv(&self, x: &[Interval]) -> Vec<Interval> {
        self.rows
            .iter()
            .map(|row| {
                row.iter().fold(Interval::point(0.0), |acc, &(c, w)| {
                    acc + Interval::point(w) * x[c]
                })
            })
            .collect()
    }

    fn apply_t_iv(&self, y: &[Interval]) -> Vec<Interval> {
        let mut out = vec![Interval::point(0.0); self.ncols];
        for (r, row) in self.rows.iter().enumerate() {
            for &(c, w) in row {
                out[c] = out[c] + Interval::point(w) * y[r];
            }
        }
        out
    }
}

fn iv_dot(a: &[Interval], b: &[Interval]) -> Interval {
    a.iter()
        .zip(b)
        .fold(Interval::point(0.0), |acc, (x, y)| acc + *x * *y)
}

/// An outward-rounded bound on `|⟨Av, w⟩ − ⟨v, Aᵀw⟩|` for the
/// exact seeded probes evaluated here. This is a structural transpose
/// diagnostic, not a global residual enclosure and not a gradient proof.
///
/// # Errors
/// Refuses malformed sparse storage or a probe request outside the bounded
/// resource envelope before allocating or indexing.
pub fn adjoint_residual_bound(op: &SparseLinear, probes: usize) -> Result<f64, GradientCertError> {
    let entries = op.validated_entry_count()?;
    if !(1..=MAX_ADJOINT_RESIDUAL_PROBES).contains(&probes) {
        return Err(GradientCertError::InvalidCount {
            field: "adjoint residual probes",
            value: probes,
            max: MAX_ADJOINT_RESIDUAL_PROBES,
        });
    }
    let n_out = op.rows.len();
    let components_per_probe =
        op.ncols
            .checked_add(n_out)
            .ok_or(GradientCertError::WorkBudgetExceeded {
                operation: "adjoint residual probes",
                requested: usize::MAX,
                max: MAX_PROBE_COMPONENTS,
            })?;
    let requested =
        probes
            .checked_mul(components_per_probe)
            .ok_or(GradientCertError::WorkBudgetExceeded {
                operation: "adjoint residual probes",
                requested: usize::MAX,
                max: MAX_PROBE_COMPONENTS,
            })?;
    if requested > MAX_PROBE_COMPONENTS {
        return Err(GradientCertError::WorkBudgetExceeded {
            operation: "adjoint residual probes",
            requested,
            max: MAX_PROBE_COMPONENTS,
        });
    }
    let entry_visits = entries
        .checked_mul(2)
        .and_then(|visits_per_probe| visits_per_probe.checked_mul(probes))
        .ok_or(GradientCertError::WorkBudgetExceeded {
            operation: "adjoint residual sparse-entry visits",
            requested: usize::MAX,
            max: MAX_ADJOINT_RESIDUAL_ENTRY_VISITS,
        })?;
    if entry_visits > MAX_ADJOINT_RESIDUAL_ENTRY_VISITS {
        return Err(GradientCertError::WorkBudgetExceeded {
            operation: "adjoint residual sparse-entry visits",
            requested: entry_visits,
            max: MAX_ADJOINT_RESIDUAL_ENTRY_VISITS,
        });
    }
    let mut state = 0x0dd5_eed5_u64;
    let mut lcg = move || {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        ((state >> 11) as f64) / (1u64 << 53) as f64 - 0.5
    };
    let mut worst = 0.0f64;
    for _ in 0..probes {
        let v: Vec<Interval> = (0..op.ncols).map(|_| Interval::point(lcg())).collect();
        let w: Vec<Interval> = (0..n_out).map(|_| Interval::point(lcg())).collect();
        let lhs = iv_dot(&op.apply_iv(&v), &w);
        let rhs = iv_dot(&v, &op.apply_t_iv(&w));
        let residual = (lhs - rhs).abs();
        // The enclosure's upper end bounds the residual soundly.
        worst = worst.max(residual.hi());
    }
    Ok(worst)
}

/// A sealed finite-difference check batch bound to its exact explicit context.
/// Only [`fd_spot_checks`] can construct one; callers can inspect but cannot
/// fabricate or mutate its verdicts/context digest.
///
/// ```compile_fail
/// use fs_adjoint::certs::FdCheckBatch;
/// let _forged = FdCheckBatch {
///     verdicts: Vec::new(),
///     objective_identity: "objective:forged".to_string(),
///     context_digest: "0".repeat(64),
/// };
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct FdCheckBatch {
    verdicts: Vec<FdVerdict>,
    objective_identity: String,
    context_digest: String,
}

impl FdCheckBatch {
    /// Read-only falsifier verdicts.
    #[must_use]
    pub fn verdicts(&self) -> &[FdVerdict] {
        &self.verdicts
    }

    /// Caller-declared objective identity bound into the context digest.
    #[must_use]
    pub fn objective_identity(&self) -> &str {
        &self.objective_identity
    }

    /// Domain-separated digest of objective identity, exact point/gradient
    /// bits, seed, direction count, and every verdict bit.
    #[must_use]
    pub fn context_digest(&self) -> &str {
        &self.context_digest
    }
}

/// One gradient's certificate: color + sealed diagnostics.
///
/// Certificate fields are private so a raw public [`FdVerdict`] cannot be
/// inserted by struct construction. Use the read-only accessors.
///
/// ```compile_fail
/// use fs_adjoint::certs::GradientCertificate;
/// use fs_evidence::Color;
/// let _forged = GradientCertificate {
///     color: Color::Verified { lo: 0.0, hi: 0.0 },
///     residual_bound: Some(0.0),
///     fd_checks: None,
///     anchor: None,
///     discontinuity: None,
/// };
/// ```
#[derive(Debug, Clone, PartialEq)]
pub struct GradientCertificate {
    /// The Proposal-3 color.
    color: Color,
    /// The sampled, outward-rounded transpose-residual diagnostic, where valid.
    residual_bound: Option<f64>,
    /// The sealed FD spot-check batch (the falsifier's evidence).
    fd_checks: Option<FdCheckBatch>,
    /// Bounded caller-declared anchor metadata, retained for diagnostics only.
    /// Presence does not authenticate the dataset or mint `Validated`.
    anchor: Option<Anchor>,
    /// The discontinuity flag inherited from the routing grade.
    discontinuity: Option<Vec<String>>,
}

impl GradientCertificate {
    /// Honest evidence color.
    #[must_use]
    pub fn color(&self) -> &Color {
        &self.color
    }

    /// Sampled transpose-residual diagnostic, when finite and non-negative.
    #[must_use]
    pub fn residual_bound(&self) -> Option<f64> {
        self.residual_bound
    }

    /// Sealed finite-difference batch, when one was supplied.
    #[must_use]
    pub fn fd_checks(&self) -> Option<&FdCheckBatch> {
        self.fd_checks.as_ref()
    }

    /// Structurally valid caller anchor retained only as metadata.
    #[must_use]
    pub fn anchor(&self) -> Option<&Anchor> {
        self.anchor.as_ref()
    }

    /// Declared discontinuity crossings, when present.
    #[must_use]
    pub fn discontinuity(&self) -> Option<&[String]> {
        self.discontinuity.as_deref()
    }

    /// True when every FD spot check agreed.
    #[must_use]
    pub fn fd_all_consistent(&self) -> bool {
        self.fd_checks.as_ref().is_some_and(|batch| {
            !batch.verdicts.is_empty()
                && batch
                    .verdicts
                    .iter()
                    .all(|verdict| fd_verdict_is_well_formed(verdict) && verdict.consistent)
        })
    }
}

fn fd_context_digest(
    objective_identity: &str,
    x: &[f64],
    grad: &[f64],
    directions: usize,
    seed: u64,
    verdicts: &[FdVerdict],
) -> String {
    let mut payload = Vec::new();
    push_bytes(&mut payload, objective_identity.as_bytes());
    push_len(&mut payload, x.len());
    for value in x {
        payload.extend_from_slice(&value.to_bits().to_le_bytes());
    }
    push_len(&mut payload, grad.len());
    for value in grad {
        payload.extend_from_slice(&value.to_bits().to_le_bytes());
    }
    payload.extend_from_slice(&seed.to_le_bytes());
    push_len(&mut payload, directions);
    push_len(&mut payload, verdicts.len());
    for verdict in verdicts {
        payload.extend_from_slice(&verdict.adjoint_dd.to_bits().to_le_bytes());
        payload.extend_from_slice(&verdict.fd_coarse.to_bits().to_le_bytes());
        payload.extend_from_slice(&verdict.fd_fine.to_bits().to_le_bytes());
        payload.extend_from_slice(&verdict.tolerance.to_bits().to_le_bytes());
        payload.push(u8::from(verdict.consistent));
    }
    fs_blake3::hash_domain(FD_CONTEXT_DOMAIN, &payload).to_string()
}

fn validate_fd_perturbations(
    x: &[f64],
    direction_values: &[f64],
    direction: usize,
) -> Result<(), GradientCertError> {
    if direction_values.iter().all(|value| *value == 0.0) {
        return Err(GradientCertError::InvalidFdVerdict {
            direction,
            field: "all-zero sampled direction",
        });
    }
    for (component, (&point, &direction_value)) in x.iter().zip(direction_values).enumerate() {
        if direction_value == 0.0 {
            continue;
        }
        for (step, scale, sign) in [
            ("coarse-plus", 1e-5, 1.0),
            ("coarse-minus", 1e-5, -1.0),
            ("fine-plus", 0.5e-5, 1.0),
            ("fine-minus", 0.5e-5, -1.0),
        ] {
            let perturbed = point + sign * scale * direction_value;
            if !perturbed.is_finite() {
                return Err(GradientCertError::UnrepresentablePerturbation {
                    direction,
                    component,
                    step,
                    reason: "perturbed coordinate is non-finite",
                });
            }
            if perturbed.to_bits() == point.to_bits() {
                return Err(GradientCertError::UnrepresentablePerturbation {
                    direction,
                    component,
                    step,
                    reason: "perturbation rounded back to the unperturbed coordinate",
                });
            }
        }
    }
    Ok(())
}

fn validate_fd_inputs(
    objective_identity: &str,
    x: &[f64],
    grad: &[f64],
    directions: usize,
) -> Result<(), GradientCertError> {
    if let Some(reason) = color_leaf_identity_reason(objective_identity) {
        return Err(GradientCertError::InvalidObjectiveIdentity { reason });
    }
    if !(1..=MAX_FD_DIRECTIONS).contains(&directions) {
        return Err(GradientCertError::InvalidCount {
            field: "finite-difference directions",
            value: directions,
            max: MAX_FD_DIRECTIONS,
        });
    }
    if x.len() != grad.len() {
        return Err(GradientCertError::DimensionMismatch {
            point: x.len(),
            gradient: grad.len(),
        });
    }
    if !(1..=MAX_GRADIENT_DIMENSION).contains(&x.len()) {
        return Err(GradientCertError::InvalidCount {
            field: "gradient dimension",
            value: x.len(),
            max: MAX_GRADIENT_DIMENSION,
        });
    }
    let requested =
        directions
            .checked_mul(x.len())
            .ok_or(GradientCertError::WorkBudgetExceeded {
                operation: "finite-difference directions",
                requested: usize::MAX,
                max: MAX_PROBE_COMPONENTS,
            })?;
    if requested > MAX_PROBE_COMPONENTS {
        return Err(GradientCertError::WorkBudgetExceeded {
            operation: "finite-difference directions",
            requested,
            max: MAX_PROBE_COMPONENTS,
        });
    }
    let mut gradient_l1 = 0.0f64;
    for (index, (&point, &gradient)) in x.iter().zip(grad).enumerate() {
        if !point.is_finite() {
            return Err(GradientCertError::InvalidVectorValue {
                field: "point",
                index,
                reason: "component must be finite",
            });
        }
        if !gradient.is_finite() {
            return Err(GradientCertError::InvalidVectorValue {
                field: "gradient",
                index,
                reason: "component must be finite",
            });
        }
        gradient_l1 += gradient.abs();
        if !gradient_l1.is_finite() || gradient_l1 > MAX_OPERATOR_L1_NORM {
            return Err(GradientCertError::InvalidVectorValue {
                field: "gradient",
                index,
                reason: "L1 norm exceeds the safe directional-derivative range",
            });
        }
    }
    Ok(())
}

/// The mandatory FD spot checks: seeded random directions through the
/// falsifier pairing (`adjoint-gradient` → `finite-difference-spot-
/// check`). Deterministic directions; conditioning-aware tolerances.
///
/// # Errors
/// Refuses mismatched/non-finite vectors, non-finite objective responses, or a
/// direction request outside the bounded resource envelope.
pub fn fd_spot_checks(
    objective_identity: &str,
    f: &dyn Fn(&[f64]) -> f64,
    x: &[f64],
    grad: &[f64],
    directions: usize,
    seed: u64,
) -> Result<FdCheckBatch, GradientCertError> {
    validate_fd_inputs(objective_identity, x, grad, directions)?;
    let mut state = seed;
    let mut lcg = move || {
        state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        ((state >> 11) as f64) / (1u64 << 53) as f64 - 0.5
    };
    let mut verdicts = Vec::with_capacity(directions);
    for direction in 0..directions {
        let dir: Vec<f64> = (0..x.len()).map(|_| lcg()).collect();
        validate_fd_perturbations(x, &dir, direction)?;
        let dd: f64 = grad.iter().zip(&dir).map(|(g, d)| g * d).sum();
        let verdict = fd_falsifier(f, x, &dir, dd, 1e-5, 1e-7);
        for (field, value) in [
            ("adjoint directional derivative", verdict.adjoint_dd),
            ("coarse finite difference", verdict.fd_coarse),
            ("fine finite difference", verdict.fd_fine),
            ("finite-difference tolerance", verdict.tolerance),
        ] {
            if !value.is_finite() {
                return Err(GradientCertError::InvalidFdVerdict { direction, field });
            }
        }
        if verdict.tolerance < 0.0 {
            return Err(GradientCertError::InvalidFdVerdict {
                direction,
                field: "negative finite-difference tolerance",
            });
        }
        verdicts.push(verdict);
    }
    let context_digest =
        fd_context_digest(objective_identity, x, grad, directions, seed, &verdicts);
    Ok(FdCheckBatch {
        verdicts,
        objective_identity: objective_identity.to_string(),
        context_digest,
    })
}

/// Caller-declared anchoring metadata (Proposal 11 assimilation). This public
/// value is diagnostic input, not an authenticated source certificate.
#[derive(Debug, Clone, PartialEq)]
pub struct Anchor {
    /// The anchoring dataset's identity.
    pub dataset: String,
    /// The regime in which the anchoring holds.
    pub regime: ValidityDomain,
}

fn push_len(out: &mut Vec<u8>, len: usize) {
    out.extend_from_slice(
        &u64::try_from(len)
            .expect("a Rust allocation length fits u64")
            .to_le_bytes(),
    );
}

fn push_bytes(out: &mut Vec<u8>, bytes: &[u8]) {
    push_len(out, bytes.len());
    out.extend_from_slice(bytes);
}

fn valid_anchor_identity(anchor: &Anchor) -> Option<String> {
    if color_leaf_identity_reason(&anchor.dataset).is_some()
        || anchor.regime.bounds().is_empty()
        || anchor.regime.bounds().len() > MAX_ANCHOR_AXES
        || anchor.regime.bounds().iter().any(|(axis, &(lo, hi))| {
            color_identity_reason(axis).is_some() || !lo.is_finite() || !hi.is_finite() || lo > hi
        })
    {
        return None;
    }
    let mut payload = Vec::new();
    push_bytes(&mut payload, anchor.dataset.as_bytes());
    push_len(&mut payload, anchor.regime.bounds().len());
    for (axis, &(lo, hi)) in anchor.regime.bounds() {
        push_bytes(&mut payload, axis.as_bytes());
        payload.extend_from_slice(&lo.to_bits().to_le_bytes());
        payload.extend_from_slice(&hi.to_bits().to_le_bytes());
    }
    Some(format!(
        "derived:v2:gradient-anchor-declaration:{}",
        fs_blake3::hash_domain(ANCHOR_DIAGNOSTIC_DOMAIN, &payload)
    ))
}

fn fd_verdict_is_well_formed(verdict: &FdVerdict) -> bool {
    verdict.adjoint_dd.is_finite()
        && verdict.fd_coarse.is_finite()
        && verdict.fd_fine.is_finite()
        && verdict.tolerance.is_finite()
        && verdict.tolerance >= 0.0
}

fn context_digest_is_valid(digest: &str) -> bool {
    digest.len() == 64
        && digest
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
}

/// Record gradient diagnostics without upgrading their epistemic authority.
/// A sampled structural transpose residual and a caller-declared dataset anchor
/// are useful falsifiers/provenance, but neither proves the gradient formula or
/// authenticates experimental membership. Until a sealed, independently
/// checkable source certificate exists, this function emits only `Estimated`.
#[must_use]
pub fn certify(
    grade: &GradientGrade,
    residual_bound: Option<f64>,
    fd_checks: Option<FdCheckBatch>,
    anchor: Option<&Anchor>,
) -> GradientCertificate {
    let residual_was_supplied = residual_bound.is_some();
    let residual_bound = residual_bound.filter(|bound| bound.is_finite() && *bound >= 0.0);
    let anchor_identity = anchor.and_then(valid_anchor_identity);
    let retained_anchor = anchor_identity.as_ref().and_then(|_| anchor.cloned());
    let discontinuity = match grade {
        GradientGrade::EstimatedWithDiscontinuity { crossing, .. } => Some(crossing.clone()),
        GradientGrade::Smooth { .. } => None,
    };
    let fd_failed = fd_checks
        .as_ref()
        .into_iter()
        .flat_map(|batch| &batch.verdicts)
        .any(|verdict| !fd_verdict_is_well_formed(verdict) || !verdict.consistent);
    let color = if fd_failed {
        Color::Estimated {
            estimator: "gradient-fd-falsifier-contradiction".to_string(),
            dispersion: f64::INFINITY,
        }
    } else if discontinuity.is_some() {
        Color::Estimated {
            estimator: "gradient-discontinuity-declaration".to_string(),
            dispersion: f64::INFINITY,
        }
    } else if let Some(identity) = anchor_identity {
        Color::Estimated {
            estimator: identity,
            dispersion: f64::INFINITY,
        }
    } else if anchor.is_some() {
        Color::Estimated {
            estimator: "gradient-invalid-anchor-declaration".to_string(),
            dispersion: f64::INFINITY,
        }
    } else if let Some(bound) = residual_bound {
        Color::Estimated {
            estimator: format!(
                "derived:v2:gradient-residual-diagnostic:{:016x}",
                bound.to_bits()
            ),
            dispersion: f64::INFINITY,
        }
    } else if residual_was_supplied {
        Color::Estimated {
            estimator: "gradient-invalid-residual-diagnostic".to_string(),
            dispersion: f64::INFINITY,
        }
    } else {
        Color::Estimated {
            estimator: "gradient-without-authoritative-certificate".to_string(),
            dispersion: f64::INFINITY,
        }
    };
    GradientCertificate {
        color,
        residual_bound,
        fd_checks,
        anchor: retained_anchor,
        discontinuity,
    }
}

/// A merge-gate refusal: teaches what is missing.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GateRefusal {
    /// What failed.
    pub what: String,
}

impl std::fmt::Display for GateRefusal {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "gradient merge gate: {} — a solver (or seam) without a passing gradient \
             check cannot merge",
            self.what
        )
    }
}

/// THE CI GRADIENT GATE, extended to seam-crossing gradients: no merge
/// without a passing check.
///
/// # Errors
/// [`GateRefusal`] when FD checks are missing, context-mismatched, malformed,
/// or failing.
pub fn merge_gate(
    cert: &GradientCertificate,
    expected_context_digest: &str,
) -> Result<(), GateRefusal> {
    let Some(batch) = cert.fd_checks.as_ref() else {
        return Err(GateRefusal {
            what: "no FD spot checks were run (the falsifier pairing is mandatory)".to_string(),
        });
    };
    if !context_digest_is_valid(expected_context_digest) {
        return Err(GateRefusal {
            what: "the expected FD context digest is malformed".to_string(),
        });
    }
    if batch.context_digest != expected_context_digest {
        return Err(GateRefusal {
            what: format!(
                "FD context mismatch: batch {} does not match orchestrator expectation {}",
                batch.context_digest, expected_context_digest
            ),
        });
    }
    if let Some(bad) = batch
        .verdicts
        .iter()
        .find(|verdict| !fd_verdict_is_well_formed(verdict) || !verdict.consistent)
    {
        return Err(GateRefusal {
            what: format!(
                "an FD spot check failed (adjoint dd {} vs FD {} beyond tolerance {}): a \
                 transpose or sign bug is the likely cause",
                bad.adjoint_dd, bad.fd_fine, bad.tolerance
            ),
        });
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{GradientCertError, validate_fd_perturbations};

    #[test]
    fn perturbation_preflight_rejects_non_finite_derived_coordinates() {
        let error = validate_fd_perturbations(&[f64::MAX], &[f64::MAX], 0)
            .expect_err("overflowed derived coordinates must refuse before evaluation");
        assert!(matches!(
            error,
            GradientCertError::UnrepresentablePerturbation {
                direction: 0,
                component: 0,
                reason: "perturbed coordinate is non-finite",
                ..
            }
        ));
    }

    #[test]
    fn perturbation_preflight_rejects_an_all_zero_direction() {
        assert!(matches!(
            validate_fd_perturbations(&[1.0], &[0.0], 3),
            Err(GradientCertError::InvalidFdVerdict {
                direction: 3,
                field: "all-zero sampled direction",
            })
        ));
    }
}
