//! Deterministic Bessel functions J0/J1/Y0/Y1 and the outgoing 2D
//! Hankel functions, built EXCLUSIVELY from `fs_math` primitives
//! (`det::` transcendentals, `Dd` double-double accumulation): no
//! platform libm, and — deliberately — NO transcribed rational
//! coefficient tables. The two regimes:
//!
//! - `x <= 18`: the defining power series (DLMF 10.2.2 / 10.8.1),
//!   accumulated in double-double so the alternating-term
//!   cancellation near the crossover (peak term ~1e6 at x = 18)
//!   costs ~1e-26, not ~1e-10.
//! - `x > 18`: the classical Hankel asymptotic sums P/Q (DLMF
//!   10.17.3), whose coefficients are GENERATED by the recurrence
//!   `a_{m+1} = a_m (4 nu^2 - (2m+1)^2) / (8 (m+1))` in code —
//!   nothing to mis-copy — truncated at the smallest term (optimal
//!   truncation error ~e^{-2x} < 3e-16 at x = 18).
//!
//! Certification (tests): the EXACT Wronskian identity
//! `J1(x) Y0(x) - J0(x) Y1(x) = 2/(pi x)` over a log grid spanning
//! both regimes and the crossover; finite-difference derivatives vs
//! the recurrence identities (independent code paths); and a
//! cross-implementation oracle against fsci-special (cephes-heritage)
//! as a dev-dependency. Honest limits of that certificate
//! (review-measured with a 120-digit reference): the Wronskian is
//! structurally BLIND to common phase errors (the chi_0 - chi_1
//! difference is exactly pi/2, so half-ulp(x) phase rounding cancels
//! identically), and pointwise accuracy at LARGE argument degrades
//! as ~x*eps from representing the phase in f64 (measured ~2e-11
//! relative-to-envelope at x = 1e6, ~5e-13 at x = 1e4, under 5e-13
//! for x <= 3e3 — the certified grid). Intended kr ranges sit well
//! inside the certified band.
//!
//! Convention: with the workspace's `e^{-i omega t}` time convention
//! the OUTGOING cylindrical wave is `H0^(1)(kr) = J0 + i Y0`.

use fs_math::c64::C64;
use fs_math::dd::Dd;
use fs_math::det;

/// Series/asymptotic crossover.
const SPLIT: f64 = 18.0;
/// Series term cap (the |x| <= 18 series converges far earlier).
const MAX_TERMS: usize = 200;
/// Euler-Mascheroni constant (universal constant; certified by the
/// Wronskian + oracle tests, which both fail if it is wrong).
const EULER_GAMMA: f64 = 0.577_215_664_901_532_9;

fn ln_half_x_plus_gamma(x: f64) -> f64 {
    det::ln(x / 2.0) + EULER_GAMMA
}

/// J0 power series in double-double: `sum (-x^2/4)^k / (k!)^2`.
fn j0_series(x: f64) -> f64 {
    let z = Dd::from_f64(-(x * x)) / Dd::from_f64(4.0);
    let mut term = Dd::ONE;
    let mut sum = Dd::ONE;
    for k in 1..=MAX_TERMS {
        #[allow(clippy::cast_precision_loss)]
        let kf = k as f64;
        term = term * z / Dd::from_f64(kf * kf);
        sum = sum + term;
        if term.abs().to_f64() <= 1.0e-34 * sum.abs().to_f64().max(1.0) {
            break;
        }
    }
    sum.to_f64()
}

/// J1 power series in double-double: `(x/2) sum (-x^2/4)^k / (k! (k+1)!)`.
fn j1_series(x: f64) -> f64 {
    let z = Dd::from_f64(-(x * x)) / Dd::from_f64(4.0);
    let mut term = Dd::ONE;
    let mut sum = Dd::ONE;
    for k in 1..=MAX_TERMS {
        #[allow(clippy::cast_precision_loss)]
        let kf = k as f64;
        term = term * z / Dd::from_f64(kf * (kf + 1.0));
        sum = sum + term;
        if term.abs().to_f64() <= 1.0e-34 * sum.abs().to_f64().max(1.0) {
            break;
        }
    }
    (Dd::from_f64(0.5 * x) * sum).to_f64()
}

/// Y0 power series (DLMF 10.8.1):
/// `(2/pi) [ (ln(x/2) + gamma) J0(x) + sum_{k>=1} (-1)^{k+1} H_k
/// (x^2/4)^k / (k!)^2 ]`.
fn y0_series(x: f64) -> f64 {
    let z = Dd::from_f64(-(x * x)) / Dd::from_f64(4.0);
    let mut term = Dd::ONE;
    let mut harmonic = Dd::ZERO;
    let mut corr = Dd::ZERO;
    for k in 1..=MAX_TERMS {
        #[allow(clippy::cast_precision_loss)]
        let kf = k as f64;
        harmonic = harmonic + Dd::ONE / Dd::from_f64(kf);
        term = term * z / Dd::from_f64(kf * kf);
        let addend = -(harmonic * term);
        corr = corr + addend;
        if addend.abs().to_f64() <= 1.0e-34 * corr.abs().to_f64().max(1.0) {
            break;
        }
    }
    core::f64::consts::FRAC_2_PI * (ln_half_x_plus_gamma(x) * j0_series(x) + corr.to_f64())
}

/// Y1 power series (DLMF 10.8.1 with `psi(k+1) + psi(k+2) =
/// -2 gamma + H_k + H_{k+1}`):
/// `(2/pi) ln(x/2) J1(x) - 2/(pi x)
///  - (x/(2 pi)) sum_{k>=0} (H_k + H_{k+1}) (-x^2/4)^k / (k!(k+1)!)`
/// after absorbing the `-2 gamma` into the `ln` term.
fn y1_series(x: f64) -> f64 {
    let z = Dd::from_f64(-(x * x)) / Dd::from_f64(4.0);
    let mut term = Dd::ONE; // (-x^2/4)^k / (k!(k+1)!)
    let mut hk = Dd::ZERO; // H_k
    let mut hk1 = Dd::ONE; // H_{k+1}
    let mut sum = Dd::ZERO;
    for k in 0..=MAX_TERMS {
        if k > 0 {
            #[allow(clippy::cast_precision_loss)]
            let kf = k as f64;
            term = term * z / Dd::from_f64(kf * (kf + 1.0));
            hk = hk + Dd::ONE / Dd::from_f64(kf);
            hk1 = hk1 + Dd::ONE / Dd::from_f64(kf + 1.0);
        }
        let addend = term * (hk + hk1);
        sum = sum + addend;
        if k > 2 && addend.abs().to_f64() <= 1.0e-34 * sum.abs().to_f64().max(1.0) {
            break;
        }
    }
    core::f64::consts::FRAC_2_PI * (ln_half_x_plus_gamma(x) * j1_series(x))
        - core::f64::consts::FRAC_2_PI / x
        - core::f64::consts::FRAC_1_PI * 0.5 * x * sum.to_f64()
}

/// The Hankel asymptotic sums `P_nu(x)` and `Q_nu(x)` (DLMF 10.17.3),
/// coefficients generated by recurrence, truncated at the smallest
/// term.
fn asymptotic_pq(nu: f64, x: f64) -> (f64, f64) {
    let mu = 4.0 * nu * nu;
    let mut p = 0.0f64;
    let mut q = 0.0f64;
    // a_m / x^m with a_0 = 1; a_{m+1} = a_m (mu - (2m+1)^2)/(8(m+1)).
    let mut term = 1.0f64;
    let mut last = f64::INFINITY;
    for m in 0..64u32 {
        let mf = f64::from(m);
        if term.abs() > last {
            break; // divergence onset: stop at the smallest term
        }
        if term.abs() < 1.0e-18 {
            // Converged far below f64 epsilon (large x): the
            // remaining terms cannot move P or Q.
            if m % 2 == 0 {
                if m % 4 == 0 {
                    p += term;
                } else {
                    p -= term;
                }
            }
            break;
        }
        last = term.abs();
        if m % 2 == 0 {
            // (-1)^{m/2} term into P
            if m % 4 == 0 {
                p += term;
            } else {
                p -= term;
            }
        } else if (m - 1) % 4 == 0 {
            q += term;
        } else {
            q -= term;
        }
        term *= (mu - (2.0 * mf + 1.0) * (2.0 * mf + 1.0)) / (8.0 * (mf + 1.0) * x);
    }
    (p, q)
}

/// J and Y of order `nu` (0 or 1) via the asymptotic form, `x > SPLIT`.
fn jy_asymptotic(nu: f64, x: f64) -> (f64, f64) {
    let (p, q) = asymptotic_pq(nu, x);
    let chi = x - (2.0 * nu + 1.0) * core::f64::consts::FRAC_PI_4;
    let amp = det::sqrt(2.0 / (core::f64::consts::PI * x));
    let (s, c) = (det::sin(chi), det::cos(chi));
    (amp * (p * c - q * s), amp * (p * s + q * c))
}

/// Bessel function of the first kind, order 0 (even; all finite `x`).
#[must_use]
pub fn j0(x: f64) -> f64 {
    if x.is_nan() {
        return f64::NAN;
    }
    if x.is_infinite() {
        return 0.0;
    }
    let ax = x.abs();
    if ax <= SPLIT {
        j0_series(ax)
    } else {
        jy_asymptotic(0.0, ax).0
    }
}

/// Bessel function of the first kind, order 1 (odd; all finite `x`).
#[must_use]
pub fn j1(x: f64) -> f64 {
    if x.is_nan() {
        return f64::NAN;
    }
    if x.is_infinite() {
        return 0.0;
    }
    let ax = x.abs();
    let v = if ax <= SPLIT {
        j1_series(ax)
    } else {
        jy_asymptotic(1.0, ax).0
    };
    // Odd symmetry including the sign of zero (j1(-0.0) = -0.0).
    if x.is_sign_negative() { -v } else { v }
}

/// Bessel function of the second kind, order 0 (`x > 0`; NaN
/// otherwise, matching the real-domain definition — a DISCLOSED
/// divergence from fsci/scipy, which return -inf at exactly 0).
#[must_use]
pub fn y0(x: f64) -> f64 {
    if x.is_nan() || x <= 0.0 {
        return f64::NAN;
    }
    if x.is_infinite() {
        return 0.0;
    }
    if x <= SPLIT {
        y0_series(x)
    } else {
        jy_asymptotic(0.0, x).1
    }
}

/// Bessel function of the second kind, order 1 (`x > 0`; NaN
/// otherwise).
#[must_use]
pub fn y1(x: f64) -> f64 {
    if x.is_nan() || x <= 0.0 {
        return f64::NAN;
    }
    if x.is_infinite() {
        return 0.0;
    }
    if x <= SPLIT {
        y1_series(x)
    } else {
        jy_asymptotic(1.0, x).1
    }
}

/// Outgoing 2D Hankel function `H0^(1)(x) = J0(x) + i Y0(x)`
/// (`e^{-i omega t}` convention). Outside the domain (`x <= 0` or
/// NaN) BOTH components are NaN — never a half-valid complex
/// (review-caught: `C64(1.0, NaN)` leaked for non-positive x).
#[must_use]
pub fn hankel0_outgoing(x: f64) -> C64 {
    if x.is_nan() || x <= 0.0 {
        return C64::new(f64::NAN, f64::NAN);
    }
    C64::new(j0(x), y0(x))
}

/// Outgoing 2D Hankel function `H1^(1)(x) = J1(x) + i Y1(x)`; same
/// full-NaN domain policy as [`hankel0_outgoing`].
#[must_use]
pub fn hankel1_outgoing(x: f64) -> C64 {
    if x.is_nan() || x <= 0.0 {
        return C64::new(f64::NAN, f64::NAN);
    }
    C64::new(j1(x), y1(x))
}
