//! First executed bake-off (music bead `frankensim-music-v8-root-3ez8g.1.4`):
//! the modal-ZOH string image (`fs_couple::modal_acoustic_time`) vs the
//! fine-pHS modal bank (`fs_phs::modal_bank` under Gonzalez stepping) on ONE
//! shared string card, judged against the ANALYTIC damped-oscillator closed
//! form — an independent reference neither contender computes with.
//!
//! Physics: a plucked taut string's modal coordinates are independent
//! viscously damped oscillators. From `(q0, 0)` the exact solution is
//! `q(t) = q0 e^{-z w t} (cos(w_d t) + (z w / w_d) sin(w_d t))` with
//! `w_d = w sqrt(1 - z^2)`. QoIs are the per-mode displacement and velocity
//! after `STEPS` samples of free decay. The ZOH image implements exactly
//! this map per sample, so its residual is rounding-level; the Gonzalez
//! midpoint image carries an honest `O((w dt)^2)` phase error. Both PASS
//! their own role gates — which is precisely the keep-both outcome: the ZOH
//! image is the performance image, the pHS bank is the interconnectable
//! authority/cross-check (it composes through Dirac ports; the ZOH model
//! does not).
//!
//! The receipt is GOLDEN-PINNED: `tests/receipts/string-modal-zoh-vs-phs-bank.bakeoff`
//! is the committed evidence artifact the claims registry references
//! (`{"kind":"bakeoff", ...}` on the `string/modal-zoh/*` and
//! `string/phs-modal-bank/*` rows). If this test's regenerated bytes differ,
//! that is a golden event: explain the semantic cause and bump the file in
//! the same commit (golden-bump protocol), never loosen the comparison.

use fs_couple::bakeoff::{BAKEOFF_HASH_DOMAIN, BakeoffOutcome, BakeoffReceipt, ContenderResult};
use fs_couple::modal_acoustic_time::{
    ModalAcousticMode, ModalAcousticState, ModalAcousticTimeBudget, ModalAcousticTimeModel,
};
use fs_phs::{modal_bank, step};
use std::collections::BTreeMap;
use std::fmt::Write as _;

/// Shared string card: a light steel-ish string, three retained modes.
const LENGTH_M: f64 = 0.65;
const TENSION_N: f64 = 60.0;
const LIN_DENSITY_KG_M: f64 = 6.0e-4;
const MODES: usize = 3;
/// Small per-mode viscous damping ratios (authored fixture values).
const ZETAS: [f64; MODES] = [1.0e-3, 1.5e-3, 2.0e-3];
/// Unit modal pluck: every mode starts at this displacement, zero velocity.
const Q0: f64 = 1.0e-3;
const SAMPLE_RATE_HZ: u32 = 48_000;
const STEPS: usize = 2_400; // 50 ms of free decay.

fn omegas() -> [f64; MODES] {
    let wave_speed = (TENSION_N / LIN_DENSITY_KG_M).sqrt();
    core::array::from_fn(|k| (k + 1) as f64 * core::f64::consts::PI * wave_speed / LENGTH_M)
}

/// Exact damped-oscillator state after `t` seconds from `(Q0, 0)`.
fn analytic(omega: f64, zeta: f64, t: f64) -> (f64, f64) {
    let wd = omega * (1.0 - zeta * zeta).sqrt();
    let envelope = (-zeta * omega * t).exp();
    let q = Q0 * envelope * ((wd * t).cos() + (zeta * omega / wd) * (wd * t).sin());
    // v(t) = -Q0 e^{-zwt} (w^2/wd) sin(wd t)  (exact derivative).
    let v = -Q0 * envelope * (omega * omega / wd) * (wd * t).sin();
    (q, v)
}

fn qoi_key(kind: &str, mode: usize) -> String {
    format!("{kind}-mode-{}", mode + 1)
}

/// The shared-card digest: every number both contenders consumed, in fixed
/// order, hashed under the receipt domain.
fn shared_cards_digest() -> fs_blake3::ContentHash {
    let mut text = String::new();
    let _ = write!(
        text,
        "string-card L={LENGTH_M:e} T={TENSION_N:e} mu={LIN_DENSITY_KG_M:e} \
         modes={MODES} q0={Q0:e} rate={SAMPLE_RATE_HZ} steps={STEPS}"
    );
    for zeta in ZETAS {
        let _ = write!(text, " zeta={zeta:e}");
    }
    fs_blake3::hash_domain(BAKEOFF_HASH_DOMAIN, text.as_bytes())
}

/// Contender A: the exact-ZOH modal runtime.
fn run_modal_zoh() -> ContenderResult {
    let omegas = omegas();
    let modes = omegas
        .iter()
        .zip(ZETAS)
        .map(|(&omega, zeta)| ModalAcousticMode {
            angular_frequency_rad_s: omega,
            damping_ratio: zeta,
            pressure_per_modal_velocity: fs_math::c64::C64::new(1.0, 0.0),
        })
        .collect::<Vec<_>>();
    let mut model = ModalAcousticTimeModel::try_new(
        SAMPLE_RATE_HZ,
        modes,
        ModalAcousticTimeBudget::audible_reference(),
    )
    .expect("string modes admit under the Nyquist guard");
    let plucked = (0..MODES)
        .map(|_| ModalAcousticState {
            displacement_m_sqrt_kg: Q0,
            velocity_m_sqrt_kg_per_s: 0.0,
        })
        .collect::<Vec<_>>();
    model
        .restore_states(&plucked)
        .expect("finite pluck states restore");
    let zero_force = vec![0.0; MODES];
    for _ in 0..STEPS {
        model.step(&zero_force).expect("free decay step");
    }
    let mut measured = BTreeMap::new();
    for (mode, state) in model.states().iter().enumerate() {
        measured.insert(qoi_key("q", mode), state.displacement_m_sqrt_kg);
        measured.insert(qoi_key("v", mode), state.velocity_m_sqrt_kg_per_s);
    }
    ContenderResult {
        image: "modal-zoh".to_string(),
        owner_crates: vec!["fs-couple".to_string(), "fs-modal".to_string()],
        measured,
        states: 2 * MODES,
        steps: STEPS,
        solver_iterations: 0,
        failure_modes: vec![
            "truncated basis: missing high modes are absent, not approximated".to_string(),
            "tension is frozen per admission; a tension ramp needs re-admission".to_string(),
        ],
    }
}

/// Contender B: the fine-pHS modal bank under Gonzalez discrete-gradient
/// stepping (state layout `(q_i, p_i)` interleaved, mass-normalized).
fn run_phs_bank() -> ContenderResult {
    let omegas = omegas();
    let drive = vec![0.0; MODES]; // one dead port; free decay
    let bank = modal_bank(&omegas, &ZETAS, &drive).expect("modal bank admits");
    let mut x = vec![0.0; 2 * MODES];
    for mode in 0..MODES {
        x[2 * mode] = Q0; // q_i at even index, p_i (= v_i, mass-normalized) odd
    }
    let dt = f64::from(SAMPLE_RATE_HZ).recip();
    let u = [0.0];
    let mut newton_total = 0usize;
    for _ in 0..STEPS {
        let record = step(&bank, &x, &u, dt).expect("Gonzalez step");
        newton_total += record.newton_iters;
        x = record.x;
    }
    let mut measured = BTreeMap::new();
    for mode in 0..MODES {
        measured.insert(qoi_key("q", mode), x[2 * mode]);
        measured.insert(qoi_key("v", mode), x[2 * mode + 1]);
    }
    ContenderResult {
        image: "phs-modal-bank".to_string(),
        owner_crates: vec!["fs-phs".to_string()],
        measured,
        states: 2 * MODES,
        steps: STEPS,
        solver_iterations: newton_total,
        failure_modes: vec![
            "O((omega dt)^2) midpoint phase error at audio rate".to_string(),
            "implicit Newton solve per sample (FD Jacobian) - budget-heavy".to_string(),
        ],
    }
}

fn build_receipt() -> BakeoffReceipt {
    let omegas = omegas();
    let t = STEPS as f64 / f64::from(SAMPLE_RATE_HZ);
    let mut reference = BTreeMap::new();
    for (mode, (&omega, zeta)) in omegas.iter().zip(ZETAS).enumerate() {
        let (q, v) = analytic(omega, zeta, t);
        reference.insert(qoi_key("q", mode), q);
        reference.insert(qoi_key("v", mode), v);
    }
    BakeoffReceipt {
        filling: "string".to_string(),
        fixture: "crates/fs-couple/tests/bakeoff_string.rs free-decay 3-mode pluck".to_string(),
        shared_cards: shared_cards_digest(),
        reference,
        contenders: [run_modal_zoh(), run_phs_bank()],
        outcome: BakeoffOutcome::KeepBoth {
            scope_a: "performance image: exact per-sample map, zero solver cost".to_string(),
            scope_b: "authority/cross-check: Dirac-composable, energy-ledgered".to_string(),
        },
        rationale: "orthogonal roles (D21 keep-both default): ZOH is exact on the \
                    truncated basis at zero solver cost; the pHS bank pays Newton per \
                    sample but composes through ports and audits energy"
            .to_string(),
        listening_receipts: vec![],
    }
}

const GOLDEN: &str = "tests/receipts/string-modal-zoh-vs-phs-bank.bakeoff";

#[test]
fn string_bakeoff_receipt_is_reproduced_and_golden_pinned() {
    let receipt = build_receipt();

    // Physics gates BEFORE the golden: each contender must pass its own
    // role gate against the analytic reference, so the golden can never
    // freeze a broken run.
    let zoh = receipt.residuals(0);
    let phs = receipt.residuals(1);
    // Detailed log: per-QoI reference, both residuals — enough to re-derive
    // the verdict from the test output alone.
    for (qoi, reference) in &receipt.reference {
        eprintln!(
            "qoi={qoi} reference={reference:+.6e} zoh-resid={:.3e} phs-resid={:.3e}",
            zoh[qoi], phs[qoi]
        );
    }
    for (qoi, residual) in &zoh {
        assert!(
            *residual < 1.0e-10,
            "ZOH is the exact map; residual {residual:e} at {qoi} says the fixture \
             or the runtime broke"
        );
    }
    // The pHS contender's failure mode is the implicit-midpoint dispersion:
    // the discrete flow oscillates at w_eff = (2/dt) atan(w dt / 2), so the
    // accumulated phase error after time T is (w - w_eff) T. Pointwise state
    // residuals near a zero-crossing are unboundedly sensitive to that phase
    // (mode 3 measures ~0.5 relative here), so a blanket state band is the
    // WRONG gate. The right gate pins the error to its mechanism: extract
    // the measured per-mode phase lag from the (q, v) phasor and demand it
    // match the dispersion model within a factor-of-2 band, with the
    // energy ENVELOPE (phase-insensitive) held to its own tight band.
    let dt = f64::from(SAMPLE_RATE_HZ).recip();
    let t = STEPS as f64 * dt;
    for (mode, (&omega, zeta)) in omegas().iter().zip(ZETAS).enumerate() {
        let predicted_phase_lag = (omega - 2.0 / dt * (omega * dt / 2.0).atan()) * t;
        let wd = omega * (1.0 - zeta * zeta).sqrt();
        let (q_ref, v_ref) = analytic(omega, zeta, t);
        let q_phs = receipt.contenders[1].measured[&qoi_key("q", mode)];
        let v_phs = receipt.contenders[1].measured[&qoi_key("v", mode)];
        // Phasor angle of the decaying rotation (q, -v/wd); the analytic
        // and discrete trajectories differ by the accumulated phase lag.
        let angle_ref = (-v_ref / wd).atan2(q_ref);
        let angle_phs = (-v_phs / wd).atan2(q_phs);
        let measured_lag = {
            let raw = angle_ref - angle_phs;
            // Wrap to (-pi, pi]; lags here are far below pi by design.
            (raw + core::f64::consts::PI).rem_euclid(core::f64::consts::TAU) - core::f64::consts::PI
        };
        eprintln!(
            "mode {} phase lag: predicted={predicted_phase_lag:+.4e} rad \
             measured={measured_lag:+.4e} rad",
            mode + 1
        );
        assert!(
            measured_lag.abs() <= 2.0 * predicted_phase_lag.abs(),
            "mode {} measured phase lag {measured_lag:e} exceeds twice the \
             midpoint-dispersion prediction {predicted_phase_lag:e}; the error \
             is no longer explained by the named mechanism",
            mode + 1
        );
        assert!(
            measured_lag.abs() >= 0.5 * predicted_phase_lag.abs(),
            "mode {} measured phase lag {measured_lag:e} is below half the \
             midpoint-dispersion prediction {predicted_phase_lag:e}; either the \
             contenders are not independent or the model changed — investigate",
            mode + 1
        );
        // Energy envelope: phase-insensitive, must track the analytic decay
        // tightly (Gonzalez dissipates exactly per the discrete R ledger; the
        // small deviation is the frequency warp entering the damping product).
        let energy_ref = 0.5 * (omega * omega * q_ref * q_ref + v_ref * v_ref);
        let energy_phs = 0.5 * (omega * omega * q_phs * q_phs + v_phs * v_phs);
        let energy_residual = (energy_phs - energy_ref).abs() / energy_ref;
        eprintln!(
            "mode {} energy: ref={energy_ref:.6e} J phs={energy_phs:.6e} J \
             residual={energy_residual:.3e}",
            mode + 1
        );
        assert!(
            energy_residual < 2.0e-2,
            "mode {} pHS energy envelope residual {energy_residual:e} exceeds \
             the authored 2e-2 band; the envelope must not inherit phase error",
            mode + 1
        );
    }
    // Budget honesty: the exact map does zero solver work; Gonzalez pays.
    assert_eq!(receipt.contenders[0].solver_iterations, 0);
    assert!(
        receipt.contenders[1].solver_iterations >= STEPS,
        "Newton must run at least once per sample"
    );

    // Canonical bytes: deterministic, round-trip exact, golden-pinned.
    let bytes = receipt.to_canonical_bytes().expect("canonical encoding");
    let decoded = BakeoffReceipt::from_canonical_bytes(&bytes).expect("round trip");
    assert_eq!(receipt, decoded);
    let manifest_dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR"));
    let golden_path = manifest_dir.join(GOLDEN);
    let golden = std::fs::read(&golden_path).unwrap_or_else(|error| {
        panic!(
            "golden receipt {GOLDEN} unreadable ({error}); if this is the first \
             run, write the bytes below to that path:\n{}",
            String::from_utf8_lossy(&bytes)
        )
    });
    assert_eq!(
        bytes,
        golden,
        "regenerated receipt differs from the committed golden; this is a golden \
         event — explain the semantic cause and bump the file in the same commit.\n\
         regenerated:\n{}",
        String::from_utf8_lossy(&bytes)
    );
    eprintln!(
        "receipt content hash: {:02x?}",
        receipt.content_hash().expect("hash").0
    );
}
